### ISSUE TITLE
Missing vertical gaps in Internet Explorer <=11

### ISSUE THREAD

**Issue by Philzen** [patrickkunka/mixitup#187]
This problem exists on all examples on the [Responsive Pages tutorial page](https://mixitup.kunkalabs.com/learn/tutorial/responsive-grids/).

Interestingly enough, the example on [MixItUp Home Page](https://mixitup.kunkalabs.com/) works like a charm in all browsers i tested.

**Comment by patrickkunka** [comment]
Thanks for letting me know.

Since MixItUp doesn't have anything to do with the styling of elements, this is most likely a CSS issue  caused by an IE quirk. I can't say I took the time QA all the codepen demos on IE, but I did with the marketing site. There are probably some subtle differences to do with whitespace clearing, justification of inline-blocks etc, but definitely fixable.
