### ISSUE TITLE
Disable justify?

### ISSUE THREAD

**Issue by phillip-haydon** [patrickkunka/mixitup#194]
How can I disable justify on the last line?

I can't find anything in docs, I figured it would be part of 'layout' but nothing :(

**Comment by patrickkunka** [comment]
Hi Phillip,

The justified layout, if used, is something that is dictated by the CSS, and has nothing to do with MixItUp. The concept behind MixItUp is that it provides filtering and sorting on top of native CSS layouts rather than building layouts with JavaScript.

The layout.display configuration option is used to determine the css "display" type for shown elements (e.g. block, inline-block), as all elements should be hidden by default.
