### ISSUE TITLE
Question: Mixitup support for reactive frameworks (Meteor/Angular)

### ISSUE THREAD

**Issue by DaEckster** [patrickkunka/mixitup#195]
It seems that it'd be incredibly useful to have documentation showing how to implement MixitUp with the new reactive frameworks, I'd currently love to add it to a Meteor app I'm working on, but am unsure of how to use MixItUp as an intermediary when the reactive framework tries to inject into the DOM.

**Comment by dcworldwide** [comment]
:+1: Also need meteor support

**Comment by patrickkunka** [comment]
Hi guys - thanks for your interest.

I'm currently in the process of developing the next major version of MixItUp (v3) which will integrate much better with modern JS frameworks due to the fact we are dropping jQuery, and adding some powerful methods for adding and removing elements. Other improvements include UMD module support and promises on all operations.

These features won't make it into v2, but that's not to say it's incompatible. I'll be sure to document integration with v3 when its released, but in the mean time I'll have to leave integration documentation/tutorials for v2 up to the community.

**Comment by dcworldwide** [comment]
Thanks Patrick for the update. Is there a summary of v3 and the improvements over v2? Really keen to learn more about it. cheers
