### ISSUE TITLE
CSS3 columns issues

### ISSUE THREAD

**Issue by nickpish** [patrickkunka/mixitup#221]
I am absolutely loving this plugin, particularly being able to work with existing layouts; but I'm experiencing an issue with the way it's rendering/animating the layout upon page load and in using filters. I have an example page set up [here](http://nickpish.com/_dev/mixitup-demo/). 

I'm using a basic `inline-block` based layout, with `column-count`, and media queries for a fluid/responsive grid, and the grid items seem to bounce around a bit before settling into place when first loaded and resorted/filtered. I'm not sure if this is due to the responsive images adapting to the width/height of the grid item, or if it's just an issue with my CSS, but I've noticed that if the window size is reduced to a single column (mobile) layout the issue doesn't seem to occur at all, in fact it's quite smooth-- only problematic with two or three columns. I'm seeing this in both the latest versions of Chrome and Firefox, btw.

Are there any adjustments I can make to reduce this rendering issue? Otherwise, it's fantastic. Thanks for any assistance here.

**Comment by roccomuso** [comment]
I have the same issue.

**Comment by mjot** [comment]
same issue here

**Comment by roccomuso** [comment]
I've noticed even some kind of "blink" when the cards moves...

**Comment by pozitron57** [comment]
:+1:

**Comment by nickpish** [comment]
Any solutions? :)

**Comment by siamkreative** [comment]
I'm experiencing the same issue with Boostrap 4 cards: http://v4-alpha.getbootstrap.com/components/card/#columns

Once BS4 will be out, I would expect that plenty of people will complain about this issue. Now would be a good time to fix it @patrickkunka 👍

**Comment by patrickkunka** [comment]
Hi all,

Thanks for the feedback. I had another look at this today, as its been a while.

Essentially, MixItUp 2 and 3 _are_ compatible with CSS3 columns layouts – with a few caveats, which is why I no longer recommend it as a layout approach.

I've put together an up-to-date demo with v3, which you can check out here:

https://demos.kunkalabs.com/mixitup/grid-columns/

The caveats you need to be aware of are as follows:

#### Elements jumping during transitions

This is caused by MixItUp transitioning the container height during an operation. As far as I can understand, this interferes with the algorithm that the browser uses to determine the column packing which in turn breaks MixItUp's geometry calculations. Essentially the browser tries to re-pack the columns while the MixitUp animation is in progress. This only appears to be an issue when the height changes substantially between operations. Without resorting to something hacky like absolute positioning (which goes against MixItUp's raison-d'être), I don't think this is something that can be fixed, but I will try to give it some further thought anyway.

The interim solution therefore, is simply to disable container height transitioning which can be done by setting the configuration option `animation.animateResizeContainer` to `false`.

This means that if you intend to use a column-based layout with MixItUp, a full-screen type design with no content below the grid (as per the above demo) is preferable so that the abrupt jumping of container height is not noticeable.

Alternatively, if you know the max-height of your container, setting a static container height may also be an option (you could use the pagination extension to throttle the container height if you had a lot of content).

#### Flickering of elements during filter in/out

This appears to be a webkit-specific rendering bug related to CSS3 columns. I have found the following hack to be effective against it:

```css
.mix {
    ...
    backface-visibility: hidden; /* Prevents flicker in Chrome */
    will-change: transform, opacity; /* Prevents flicker in Safari */
}
```

As with these things however, we have no guarantee that they will work forever, or that the browser's rendering behavior won't change in the future.

I hope that helps!

**Comment by siamkreative** [comment]
The main issue that remains is that the elements are displayed in columns when sorted haha (starting from the left column). This doesn't look good. Is there anything to do about it? Would you recommend another library that works out of the box with CSS3 columns?

I actually think that I might have to switch to absolute positioning, forget about CSS3 columns and use Isotope to achieve a masonry layout with filters.

**Comment by patrickkunka** [comment]
Yes that's the intended behaviour of CSS3 columns - and MixItUp will always respect the native the behaviour. I would recommend you take a look at Isotope as sounds like a masonry layout is what you need (not CSS3 columns).

**Comment by jklue** [comment]
As a workaround, I disabled `animation` and then the CSS3 columns work fine.
