### ISSUE TITLE
Terrible support

### ISSUE THREAD

**Issue by aolko** [patrickkunka/mixitup#226]
The support forums are very inactive, plus, *of course*, you can't email to the developer directly.

**Comment by patrickkunka** [comment]
I'm sorry for your frustration but I'm just one guy and I have a family, a full time job and software company to run.  I'm currently dedicating what little free time I have to getting MixItUp 3 production ready and as well documented as possible for a launch early next year, which will feature an entirely new approach to support.

It is clearly stated in numerous places that support can not be guaranteed and this has always been the case. There are always resources available such as the wider community and stack overflow, and although I no longer have time to be active on the support forums, many of our users are kind enough to help each other out. Finally, there is nothing stopping you from emailing me politely and asking for help as many people do, rather than creating unconstructive Github issues such as this.
