### ISSUE TITLE
MixItUp Appending Objects in reverse

### ISSUE THREAD

**Issue by peterph-am** [patrickkunka/mixitup#235]
I'm appending some ajaxed objects to my mixitup container, however the objects are being appended in reverse order.

This is my code: 

```
$.each(data, function(i, obj) {
        // jQuery object using data array
        var $item = $(_tileTemplate(obj));

        // Append new items to the mixItUp container
        $el.itemContainer.mixItUp('append', $item);
    });
```

The order of my data is right also.

**Comment by patrickkunka** [comment]
Hello Peter,

I suspect this is due to the fact that 'append' (or its low level method 'insert') is an asynchronous method, but you are performing your inserts in a synchronous loop. In other words, if you have animation enabled for your MixItUp instance, you will need to wait for each insert to start before inserting the next one.

Alternatively, you can append multiple elements in one operation, in the form of a jQuery collection, which is the preferred way of doing this. 

For example:

```js

var $collection = $();

$.each(data, function(i, obj) {
    // jQuery object using data array
    var $item = $(_tileTemplate(obj));

    // Append new items to the collection

    $collection.add($item);
});
```
$el.itemContainer.mixItUp('append', $collection);

Let me know if that helps.
