### ISSUE TITLE
MixItUp MultiFilter: Bootstrap select with "live search" treated as text input

### ISSUE THREAD

**Issue by dreedijk** [patrickkunka/mixitup#269]
When adding a bootstrap select with search option, MixitUp multifilter throws an error in the console:

**Error: [MixItUp MultiFilter] A valid `data-search-attribute` must be present on text inputs**

This causes unexpected and unwanted behaviour because the value selected is not applied and the select options are removed.

**Comment by patrickkunka** [comment]
Because the MultiFilter extension listens for `keyup` events on each filter group, typing into the search box in a bootstrap select will cause MixItUp to incorrectly identify the input as a text input rather than a select input.

Unfortunately there's not much we can do in MixItUp to prevent this other than writing hacky bootstrap-specific code which I'd like to avoid.

Instead, I would suggest adding code to prevent the `keyup` event from "propagating" from the bootstrap select, and reaching the filter group's handler.

Firstly, wrap your select in a div or other containing element:

```html
<fieldset filter-group>
    <div class="bootstrap-select-wrapper">
        <select>..</select>
    </div>
</fieldset>
```

Then setup an event handler on that element to prevent the `keyup` event from propagating:

```js
var bootstrapSelectWrappers = Array.from(document.querySelectorAll('.bootstrap-select-wrapper'));

function handleBootstrapKeyup(e) {
    e.stopPropagation();
}

bootstrapSelectWrappers.forEach(function(el) {
    el.addEventListener('keyup', handleBootstrapKeyup);
});
```

or with jQuery

```js
$('.bootstrap-select-wrapper').keyup(function(e) {
    e.stopPropagation();
});
```

Let me know if that works!

**Comment by dreedijk** [comment]
Unfortunately it doesn't. With the javascript code, I'm getting:
`ReferenceError: Can't find variable: handleBootstrapKeyUp`

With the jQuery code, I'm still getting:
`Error: [MixItUp MultiFilter] A valid data-search-attribute must be present on text inputs`
on each input.

**Comment by patrickkunka** [comment]
Was almost there, but there's a few more events we need to handle that are coming from the bootstrap select. I've managed to get it working with the following code:

```html
<fieldset data-filter-group>
    <span class="select-wrapper">
        <select class="selectpicker" data-live-search="true">
            <option value="">Color</option>
            <option value=".green">Green</option>
            <option value=".blue">Blue</option>
            <option value=".pink">Pink</option>
        </select>
    </span>
</fieldset>
```

```js
var $selects = $('.selectpicker'); // cache selects
var $selectWrappers = $('.select-wrapper'); // cache select wrappers

$('form').on('reset', function() { // update bootstrap selects on form reset
    $selects.val('').selectpicker('refresh');
});

$selects.selectpicker(); // init bootstrap selects

$selectWrappers.on('keyup change', function(e) { // cancel keyup and change events from propagating from the bootstrap selects
    if ($(e.target).is('input, button')) {
        e.stopPropagation();
    }
});
```
