### ISSUE TITLE
MixItUp instance busy error on Chrome

### ISSUE THREAD

**Issue by peterfealey** [patrickkunka/mixitup#278]
On Chrome, when using filters, the first filter will display the relevant content, however subsequent clicks on filters will not continue to filter, and will generate the following error in the console:

`mixitup.min.js:17 [MixItUp] WARNING: An operation was requested but the MixItUp instance was busy. The operation was rejected because the queue is full or queuing is disabled.`

Code: 

`    	<section id="two-column-header">`
`			<a class="label label-success filter" data-filter="all">Show All</a>`
`				{% for tag in contents.gallerytags %}`
`		<a class="label label-success filter" style="margin-bottom:5px" data-filter=".{{ tag.title | remove: " " }}">{{ tag.title | upcase }}</a>`
`				{% endfor %}`
`		<div id ="mixitup">`
`			<div class="row">`
`			{% for gallery in contents.gallery_images %}`
`					<a href="{{ gallery.gallery_image.url | resize: 'x400' }}" data-toggle="lightbox" data-gallery="multiimages" data-footer="{{ gallery.caption }}" data-title="{{ gallery.title }}" data-type="image" >`
					`<img src="{{ gallery.gallery_image.url | resize: '210x210#' }}" class="img img-responsive mix {% if gallery.tags %}{% for tag in gallery.tags %}{{ tag.title | remove: " " }} {% endfor %}{% endif %}" />`
				`	</a>`
		`	{% endfor %}`
	`		</div>`
 `         </div>`
	`	</section>`
    `  <script>$(function(){  `
  `  var mixer = mixitup('#mixitup');`
`});</script>`

**Comment by peterfealey** [comment]
Sorry, needed to read further into the docs to understand queuing. Looks like the animation event never completes in my case, so the queue doesn't ever process.

**Comment by patrickkunka** [comment]
Hi @peterfealey,

Yes that makes sense. There's a few possible reasons why mixitup might not accurately detect the 'ontransitionend' event that gets fired from target elements at the end of an operation, but I'd have to take a look at your project to figure out which one.

Do you have a staging URL I could take a look at?

**Comment by peterfealey** [comment]
Hi @patrickkunka - Thanks for getting back to me, have a look at www.outposts.co.uk/gallery - For now I've just popped in a conditional that disables animations if it detects Chrome. Not ideal I know!

**Comment by patrickkunka** [comment]
Hello @peterfealey, apologies for the delay in getting back to you. I've just had a look at your site. Although you've disabled animations so I can't actually replicate the issue, your markup structure may be the underlying issue.

With MixItUp, all target elements must be siblings, but in your markup, each target element with the class '.mix' is nested within a `<a>` tag on which you have added your category class names. I'm actually surprised this still works even without animations!

Can you try moving the "mix" class name off the `img` tags and up onto the `a` tags, and see if that helps?

**Comment by patrickkunka** [comment]
Closing for now, but please let me know if you want me to reopen this.

**Comment by mohsen-sharify** [comment]
this worked for me:
http://stackoverflow.com/a/41689333/1044535

aditional: set animation faster
var mixer = mixitup(containerEl, {
                selectors: {
                    control: '[data-mixitup-control]'
                },
                animation: {
                    duration: 200
                }
            });

**Comment by Kwapi** [comment]
Had the same issue on a page with 374 items and filtering using a text input field. Disabling animations helped

**Comment by patrickkunka** [comment]
Here's some further information on what @Kwapi is referring to.

If the mixer's queue gets filled up, you'll get this error. With a text field as your user input, a common problem conerns triggering filter operations on each keystroke, which could fire several times a second depending on the typing speed.

If your mixer's animations are taking 400ms or so (plus JS/DOM overhead time for a large dataset - which increases linearly), you could easily imagine that tens of pending operations could be sitting in the queue after a few seconds of typing. Without this error being thrown, we wouldn't know this, and the user would then have to wait a very long time for the DOM to reflect the most recent search query.

The `animation.queueLimit` property lets you change the upper limit on the amount of pending operations allowed in the queue. By default it is set to 3. Once the queue is full, and a subsequent operation is requested, the above error will be thrown. This is set low to warn you about problems with your code.

The filter by text input demo (https://demos.kunkalabs.com/mixitup/filtering-by-text-input/) "throttles" the keyup event so that a request can only occur once typing has stopped for 350ms. This is a very important feature of any auto search UI that should not be removed.

With the above in mind, there are two solutions if you still find yourself hitting the limit a lot. One would be to decrease your animation duration, or disable animations completely (as @Kwapi suggested), an other would be to increase the throttle duration to a greater value than your mixer animation duration. Finally, you could increase the `queueLimit`, but you should probably avoid doing this, as there's never really a good reason to have a bunch of pending operations sitting in the queue. as ideally we want the UI to be snappy and reactive to user input.
