### ISSUE TITLE
Pagination error - How do I create a reference? 

### ISSUE THREAD

**Issue by KimiEatsCode** [patrickkunka/mixitup#279]
mixitup.js:359 [MixItUp] WARNING: This element already has an active MixItUp instance. The provided configuration object will be ignored. If you wish to perform additional methods on this instance, please create a reference.

**Comment by patrickkunka** [comment]
Hi @SarahMcAleer,

When you instantiate a mixer, the `mixitup()` factory function returns a reference to that mixer which you can save as a variable and use later if want to interact with your mixer via its API.

`var mixer = mixitup('.container');`

Then later on if you need to call an API method, you use the mixer variable:

`mixer.filter('none');`

This is more efficient/performant than repeatedly calling the factory function - e.g: `mixitup('.container').filter('none')`, every time you want to interact with your mixer. Which is why the warning is fired, as it probably indicates a misunderstanding of the factory function in your code.

The other possible scenario for this warning, (especially if you are not using the API but are still seeing this warning), would be that you are not garbage collecting your mixer instance. This might be the case if you are building a single page app and you are rendering your application views/components in the browser with JavaScript.

If that sounds like a possibility, be sure to call:

`mixer.destroy()` when your component is detached, or your view changes. Your framework should provide hooks to do this.

Hope that helps

**Comment by KimiEatsCode** [comment]
Wow thanks for the quick reply. I am new to javascript so I'll look over your comment and see what I can understand. The previous developer used the mixitup plugin on the website but I saw she did not have the mixitup.js file in the js folder. When I added the mixitup.js file to the js folder this is when I get the error.

**Comment by patrickkunka** [comment]
OK - its possible the previous developer might have been using a CDN to host the mixitup file.

This warning is related to how you interact with MixItUp in your own JavaScript code however, so it shouldn't have anything to do with where the file is located. I would look to see where in your project you are instantiating MixItUp, as this will be the source of the warning.

Also - it is only a warning (not an error) so you can safely ignore it, as long as it is not breaking your project.
