### ISSUE TITLE
css transition issues on target

### ISSUE THREAD

**Issue by szyam** [patrickkunka/mixitup#281]
Hello, I'm noticing now with v3 that when I add a css transition effect for hover on the same element I'm targeting with mixitup, it acts kind of erratic. I would like to be able to use transition on the element for ui purposes but not sure how to go about doing since it appears mixitup is now using it too. We've been using for a while and do have a license. Thanks

**Comment by patrickkunka** [comment]
Hi @szyam,

This isn't new to v3, but CSS3 transitions should be avoided directly on target elements, as this will intefere with MixItUp's ability to detect `transitionend` events being dispatched from targets accurately.

The workaround is to nest your markup inside your target elements, and apply your transitions to that nested element instead of the target root.

You'll notice in our sandbox demo at https://www.kunkalabs.com/mixitup/ when you toggle on "delete" mode, the transform animation is applied to an `:after` psuedo element nested inside the target root for this reason.

I hope that helps.

**Comment by patrickkunka** [comment]
Assuming this worked for you but let me know if not and can reopen.
