### ISSUE TITLE
Custom filter combined with css selectors

### ISSUE THREAD

**Issue by ToasterBR** [patrickkunka/mixitup#283]
Hi @patrickkunka !

Recently we acquired mixitup-multifilter and I would like to know if it's possible to make a selection box with custom filters?

In my current project, I have 5 select boxes. 2 of them (Idade and Patente, which means Age and Rank) check for values below a number. The rest just uses css classes.

![Imgur](http://i.imgur.com/M4oVZpe.png)

I managed to use the filter method to gather all elements into an array, but I'm having a hard time to make it work with other filters (selector ones, like classes).

To get the elements I needed, I used:

```
var collection = Array.from(document.querySelectorAll('#card'));

var customFilters = {
      ageCheck2: collection.filter(function(target) {
          var age = $(target).find('.card-age-value').text();
          return parseInt( age, 10 ) <= 14;
      });
}
```

In all examples that I could find, there is none using custom filters. Maybe I just left something out?

Could you provide an example using 2 or more select boxes, using custom filters and regular ones(css)? 

Also, It would be great if the select boxes uses the AND logic between them. I believe this is the default behavior, right?

Thanks!

**Comment by patrickkunka** [comment]
Hi @ToasterBR,

Unfortunately, the purpose of the MultiFilter extension is specifically to manage the concatenation algorithm concerned with joining DOM selector strings in various logical combinations.

Therefore, you won't be able to use it with inputs that don't output some form of selector string.

For your project, your best bet would be to build your UI in an entirely custom way, where each active select option reduces the initial collection further, according to some custom filter function as per your example above.

Perhaps something like the following (not tested):

```js
const form = document.querySelectorAll('.filter-form');

// Construct an array where each item contains a reference to a <select>
// option and its associated filter function:

const filters = [
    // Example of a custom filter, e.g. age range
    {
        el: document.querySelector('.age-select'),
        fn: (value, targetEl) => {
            const age = parseInt(targetEl.getAttribute('data-age')); // e.g. 13
            
            return age <= value;
        }
    },
    // Example of a standard DOM selector filter e.g. color
    {
        el: document.querySelector('.color-select'),
        fn: (value, targetEl) => targetEl.matches(value) // e.g. '.green'
    },
    ... // Any number of additional filters using the above structure
];

function filterMixer() {
    // Create an initial collection containing all elements
    
    let collection = Array.from(document.querySelectorAll('.card'));

    // For each item in the filters array, filter the collection by that value

    filters.forEach(filter => {
        const value = filter.el.value;

        // If the <select> is not selected, continue to the next without filtering

        if (!value) return; 

        // Else, filter the collection using the provided function

        collection = collection.filter(filter.fn.bind(value));
    });

    // Pass the final collection to your mixer
    // (the mixitup .filter() API also accepts an array of DOM elements)

    return mixer.filter(collection);
};

// Assuming all <select> options are nested in a single element
// (e.g. a <form>), we can bind a single `change` event handler to it

form.addEventListener('change', filterMixer);
```

I hope that makes sense!

Also, since it sounds like the MultiFilter extension isn't going to be able to do quite what you need it for, please let me know if you'd like a refund via our contact form and I'd be happy to sort that out.

**Comment by patrickkunka** [comment]
Assuming this worked for you, but please let me know if you want me to reopen.

**Comment by ToasterBR** [comment]
Hi @patrickkunka!
I didn`t have a chance to work in the project yet, so next week I'll test this code.
Thanks for the answer!

**Comment by ToasterBR** [comment]
Hello again, @patrickkunka!

I'm having some trouble implementing  this code. It seems it works, but I'm a little lost in the HTML structure that you suggested.

Also, in this part of the code:
```
{
        el: document.querySelector('.age-select'),
        fn: (value, targetEl) => {
            const age = parseInt(targetEl.getAttribute('data-age')); // e.g. 13
            
            return age <= value;
        }
    },
```
Which element targetEl is referencing? Is .age-select the classname of the select box?

Thanks again!

**Comment by patrickkunka** [comment]
Hi,

So `targetEl` is the MixItUp target element. It is one item in the collection returned from the line

```js
let collection = Array.from(document.querySelectorAll('.card'));
```

Typically this would be queried by `'.mix'` or the target selector specified in your configuration. I've used `'.card'` as this seems to be what you're using. NB: Your initial example queried by `'#card'` but I have changed it to a class selector rather than an ID selector, as IDs must be globally unique so I'm guessing that's a typo.

Yes `'.age-select'` is a hypothetical class attached to your `<select>` element, although you could query this however you like. In each object in the `filters` array, the `el` property contains a reference to the `<select>` element for that dimension. Perhaps `selectEl` would have made more sense as the prop name.

Hope that helps.
