### ISSUE TITLE
Only first container works

### ISSUE THREAD

**Issue by mortennh** [patrickkunka/mixitup#286]
I'm having a list of items which are grouped in years. You can either filter by year and by name/category. Filtering by year works fine but filtering by name/category only affects the first container. 

let mixerYear =  mixitup('.mixitup-pub-container', {
  selectors: {
    control: '.yearfilter',
    target: '.mix--year'
  }
});

let mixerName =  mixitup('.mixitup-item-container', {
  selectors: {
    control: '.namefilter',
    target: '.publication__item'
  }
});

I have a fiddle prepared so you can try it out and see what i mean.

https://jsfiddle.net/t6ytjxzq/

What did i forget?

**Comment by patrickkunka** [comment]
Hi @moesphemie,

You're almost there, but unlike MixItUp 2's jQuery API which wrapped a jQuery collection of one or more elements, MixItUp 3 "mixers" represent a single container only.

Therefore, for your `.mixitup-item-container` – which occurs multiple times in your markup – you would need to instantiate a new mixer for each one.

```js
const itemContainers = Array.from(document.querySelectorAll('.mixitup-item-container'));

const config = {
  selectors: {
    control: '.namefilter',
    target: '.publication__item'
  }
};

const mixers = itemContainers.map(container => mixitup(container, config));
```
I've updated your fiddle with the above code here: https://jsfiddle.net/t6ytjxzq/1/ and it appears to be working as intended.

Alternatively, there is also an undocumented 4th parameter which can be passed to the `mixitup()` factory function which can be used to return a  jQuery-like "collection" instead of instance. We use this internally to wrap register mixitup as  jQuery plugin so that the v2 API can still be used.

To use this, you can call mixitup like this:

```js
const mixerCollection =  mixitup('.mixitup-item-container', {
  selectors: {
    control: '.namefilter',
    target: '.publication__item'
  }
}, void 0, true);
```

NB: third paramater is a reference to an optional iframe, so is omitted by passing `void 0`. You can then use your collection to perform operations on multiple instance simultaneously just as you would the jQuery api:

 ```js
mixerCollection.mixitup('filter', '.cat-1');
```

Here's your fiddle updated with this approach: https://jsfiddle.net/t6ytjxzq/2/, and also works as expected.

It's up to you which approach want to take. As the second option is not part of our public API it may change in the future, so I'd probably recommend using the first option.

Hope that helps.

**Comment by mortennh** [comment]
Hey @patrickkunka thank you very much for your great answer :) I figured out that it would be solved by working with an array but i just couldn't come up with the right approach! Now it makes sense and I've learned something new. Thank you
