### ISSUE TITLE
Angular 2 implementation

### ISSUE THREAD

**Issue by eliteproxy7** [patrickkunka/mixitup#287]
love the component! trying to implement this in my Angular 2 app having some issues

1. I installed using "npm install --save-dev mixitup" and the mixitup folder is in my node_modules folder
2.  in my app.components.ts i added  import { mixitup } from 'mixitup';

I get 

ERROR in /Users/venmkhm/Desktop/Working/angular/ts/src/app/app.component.ts (3,25): Cannot find module 'mixitup'.)
webpack: Failed to compile.

thank you

**Comment by patrickkunka** [comment]
Hi @eliteproxy7 

It should be

```js
import mixitup from 'mixitup';
```

There is just one default export (`mixitup`) which you can call whatever you like.

Also please let me know how you get on with integrating into Angular 2. You'll probably want to look at MixItUp 3's Dataset API if you haven't already.

I'm currently working on an extension to enable integration with React, which is necessary because React doesn't like other libraries touching the DOM so there are a couple of workarounds required. With that in mind I'd be curious to see if it will work out of the box with Angular 2 (which I haven't used myself yet), so please share your integration once/if you get it working!

Will leave this issue open.

**Comment by ghost** [comment]
I'd love an angular2 implementation of this! (I'm not a good programmer enough for such an endeavor though).

**Comment by LawJolla** [comment]
@patrickkunka Incredible work!

I'm considering hacking something together to work React with refs.  I've used Greensock's animation library with React successfully -- it seems like as long as the DOM tree isn't changed, React is fine with style changes.

That said, I'd rather wait for your solution.  Are you anticipating a release soon?

**Comment by patrickkunka** [comment]
HI @LawJolla,

I'm specifically integrating with the Dataset API which means MixItUp will manipulate the DOM tree, which makes things particularly tricky, but not impossible! I had made quite a bit of progress, then I hit a wall with the way React deals with event binding, so I might need to go back and rethink some things. I think because of that (and also because I'm pretty busy right now), it might still be a while off. So feel free to forge ahead with your own experiments.

**Comment by NikhilRadadiya** [comment]
Hey @patrickkunka ,

I'm trying to implement it in angular2, can you show me a way?

**Comment by patrickkunka** [comment]
Hi @NikhilRadadiya,

Sorry but I have no experience with Angular 2. Perhaps @eliteproxy7 can point you in the right direction?

**Comment by NikhilRadadiya** [comment]
Hey @eliteproxy7 ,

did you implement it it with angular2?

**Comment by NikhilRadadiya** [comment]
@patrickkunka It is working with static data. but when I try to load dynamic data it doesn't work

**Comment by LawJolla** [comment]
I've returned to this issue.  I love React and MixItUp.  I have it working with the data API.  The problem is (as you've alluded) I cannot attach React events because MixItUp render requires a string.  

Specifically, I'm making an image viewer. I filter thumbnails and onclick of the thumbnail, the main image should update.  But I cannot figure out how to attach a React onClick event to the MixItUp render item.

Any ideas?

**Update**

I was able to get it to work, albeit very hacky.  For anyone interested, I'll post a bin tomorrow.

**Update 2**

Here's a bin.  I hacked the code out of my larger project, so it may not be the clearest or most concise.  

http://jsbin.com/vaduvok/edit?js,output

If anyone (especially @patrickkunka ) has suggestions on ways to do it better, please tell me!

**Comment by Lyricalz** [comment]
@NikhilRadadiya can you show you how you did it with static data in angular2? I'm only able to do it with dynamic data lol using the dataset api

**Comment by MikeyBeLike** [comment]
@NikhilRadadiya for dynamic data in angular2, i'd suggest you use dataset api instead, much more easier
