### ISSUE TITLE
load filter not triggering callback

### ISSUE THREAD

**Issue by catharsisjelly** [patrickkunka/mixitup#288]
Hi there,

I'm using mixitup (3.1.5) and want to use the load configuration option. However I also need the load to trigger the `onMixEnd` callback after the load filter finishes. Is there a way to do this? Sample code below..

```
mixitup('.courses', {
    load: {
        filter: '.my-filter'
    },
    selectors: {
        target: 'article'
    },
    animation: {
        enable: false
    },
    callbacks: {
        onMixEnd: function (state) {
            // Do extra stuff
        }
    }
});

**Comment by patrickkunka** [comment]
Using the load configuration object is synchronous and only results in the creation of the initial state, rather than triggering a specific filter/sort operation.

Therefore no callbacks are triggered. Whatever code you wanted to put in your callback can be executed directly after calling the factory function.

**Comment by catharsisjelly** [comment]
Thanks for the hint @patrickkunka just for completeness my solution is as follows

```
$(function() {
    var hideCategories = function() {
        // Do stuff
    };
    mixitup('.courses', {
        load: {
            filter: '.myfilter'
        },
        selectors: {
            target: 'article'
        },
        animation: {
            enable: false
        },
        callbacks: {
            onMixEnd: hideCategories
        }
    });
    hideCategories();
});
```

Might not be the most elegant but it seems to work

**Comment by AbeCole** [comment]
This seems like incorrect behaviour, since the onMixClick callback is related to the filter targets being used. In our use case we want to trigger behaviour depending on which filter has been selected, it seems like this should happen regardless of whether the load attribute is synchronous. Or am I misunderstanding something here?

**Comment by patrickkunka** [comment]
Hi Abe, 

I see your logic. However, the way I've designed it is such that the purpose of a callbacks is to hook into specific points in the lifecycle of mixitup operations which are asynchronous. Since instantiation is synchronous, a callback should not be needed, as we can just write your code in the same callstack.

For example:

```js
function doSomethingBasedOnFilter(currentFilterSelector) {
    // trigger behaviour based on filter
}

const initialFilterSelector = '.my-category';

const mixer = mixitup(container, {
    load: {
        filter: initialFilterSelector
    },
    callbacks: {
        onMixEnd: (state) => doSomethingBasedOnFilter(state.activeFilter.selector)
    }
});

doSomethingBasedOnFilter(initialFilterSelector);
```

The above example shows how we can call some custom functionality both at instantiation, and then at the end of every operation.

Hope that makes sense.
