### ISSUE TITLE
MixItUp with MultiFilter - Active state not removed from filter triggers

### ISSUE THREAD

**Issue by afkatja** [patrickkunka/mixitup#294]
We have bought the multi filter extension and are having some problems integrating it into our project. 

A basic pen can be found here: http://codepen.io/afkatja/pen/XpvVJL. (This pen does not really work because I don't know how to include the mixitup plugin in a pen or fiddle, but you probably get the idea of what I am trying to do.)

The problem seems to be that after resetting the filters (i.e. clicking the items with property `data-filter="all"` and `data-toggle="all"`), the class `resources-filter-active` is not removed from the filter trigger. 

I made a screen capture to illustrate this problem.
![mixitup](https://cloud.githubusercontent.com/assets/708310/23167980/cd13e9ea-f846-11e6-90ba-e668163736d0.gif)

**Comment by patrickkunka** [comment]
Hi Katja,

For a reset button to work correctly with MultiFilter, you need to put your UI inside a  `<form>` element as can be seen in the included demos.

Also, you don't need `data-filter="all"` on your reset button, just `<button type="reset">`.

For clarification - when using MultiFilter, you lose the "2-way" binding between the controls and mixer which you would get with the standard controls. This is because MixItUp has no way of knowing how to break down the provided compound selectors back into the appropriate groups and keep the controls in sync. So you have to do things the MultiFilter way, which means using a reset button to clear filters, or the new API methods which are added with the extension.

**Comment by afkatja** [comment]
Hi Patrick,
Thanks for your help! It works now. Maybe you could clarify this (more) in the docs or examples?

**Comment by patrickkunka** [comment]
Great. Yes - I was thinking the same. This is a very new extension, so still ironing out the docs.
