### ISSUE TITLE
Toggle & 'and' logic

### ISSUE THREAD

**Issue by webmdt** [patrickkunka/mixitup#297]
Each 'person' has multiple "Ethnicities" assigned to them, so I'd like to create a TOGGLE for each of the Ethnicities. The logic should be AND ... so that it only returns 'persons' that meet all of the TOGGLED ethnicities.

I directly mimicked - https://demos.kunkalabs.com/mixitup/toggle-filtering-and-logic/

However, it seems to use 'or' logic, as it returns all persons that meet ANY of the Toggles. For example, if someone has only "Hi" (hispanic) ... as long as HISPANIC is toggled on, any OTHER Ethnicity chosen that person will STILL be returned. I'd like it to only display results when ALL criteria are met.

![screen shot 2017-03-08 at 1 42 31 pm](https://cloud.githubusercontent.com/assets/14183110/23718136/6cc23f14-0404-11e7-89ac-6a08b1be4808.png)

![screen shot 2017-03-08 at 1 41 20 pm](https://cloud.githubusercontent.com/assets/14183110/23718116/6064ad4c-0404-11e7-889f-c7bdb5fa0f18.png)

![screen shot 2017-03-08 at 1 41 02 pm](https://cloud.githubusercontent.com/assets/14183110/23718110/5c9e66da-0404-11e7-9ecf-0e085a5b48d4.png)

URL - http://strawhat-auditions.com/marcoApp/?page=actorSearch

On a different note, I cannot find a method to check a RANGE of values or dates. Example is imagine there is a DATA TYPE = date-date-end="06-06-2017" ... and on the front end there is a select field that has 3 options (Dates before Today ... Dates after Today ... Dates ON Today). 

My current workset, is I have TWO days "Start & End" ... so I'd like to provide users with TWO date pickers as filters ... and do "Min/Max" styling logic ... where if the FIRST DATE input == '02-02-2017" and the SECOND DATE input == '02-02-2019' ... only records with a Date between those two dates ... (less then SECOND ... and more then FIRST)

**Comment by patrickkunka** [comment]
Hi Marco,

Thanks for your questions.

Firstly, the `control.toggleLogic` configuration option does not affect the behavior of the MultiFilter extension. This is only applicable when using MixItUp's built-in controls.

When using MultiFilter, you define the logic using the `multifilter.logicWithinGroup` and `multifilter.logicBetweenGroups` configuration options. If you want to override logic for a specific group, you can do this in its markup. For example:

```html
<fieldset data-filter-group="ethnicity" data-logic="and">
```

See the section entitled "Configuring Filter Group Logic" in the following documentation for more information:

https://www.kunkalabs.com/mixitup-multifilter/docs/get-started/

Regarding your second question, MixItUp uses the DOM Selectors Level 2 API under the hood. This API does not currently implement a way of querying DOM attributes by a range, so we must write custom JavaScript functionality to do this, which requires filtering via the API rather than the built-in controls.

Unfortunately, combining custom API-based filtering functionality with the selector-based MultiFilter extension is not easily done, but you may find the following discussion helpful:

https://github.com/patrickkunka/mixitup/issues/283

**Comment by Domzw** [comment]
> When using MultiFilter, you define the logic using the multifilter.logicWithinGroup and multifilter.logicBetweenGroups
@patrickkunka  I have purchased and implemented the Multifilter extension on a webflow prototype. 
Not much of a developer, here's what I'm trying to do:

I have a select filter and filter toggles ( 3 toggles and a reset button) 
I want to be able to have an `<option> ` under the selector filter that resets everything under the selector filter AND resets the toggles

Is this possible with MixItUp + MultiFilter?

If so  are you able to please explain how? I can send you a read only link that shows what I have so far

**Comment by patrickkunka** [comment]
Hi @Domzw 

The multifilter extension expects all `<option>` within a select to be filter controls, so unfortunately, having a global reset button in here would not work.

You could have a "local" reset option, (e.g. with a `value` of `.mix`) which would essentially reset its own filter group only, but as far as reseting all form inputs for the whole mixer, you would need to use an actual reset button for that: `<button type="reset">Reset</button>`.

I hope that helps.
