### ISSUE TITLE
missing "isLoaded" from MixItUp 2

### ISSUE THREAD

**Issue by tsawitzki** [patrickkunka/mixitup#300]
Hello,

I kind of miss the "isLoaded" state functionality in MixItUp 3 or maybe I just didn't get the point with new API and states:
In my HTML template I am fetching pages dynamically via AJAX with jQuery, which means I can't simply hook a new initialization to the DOM-ready any more and once an instance of MIU has been created its dead after I navigate back to the site that contains it. 

So what I used to do with MIU 2 was to ask if an instance already exists, then destroy it and re-initialize it, kind of like this:

```
if(!$container.mixItUp('isLoaded')){
  $container.mixItUp('destroy'); // destroy first
  $container.mixItUp(...) // then re-initialize
}
```

What I don‘t seem to get is what this state is called in MIU 3 and what the syntax is to re-create the above if-statement

**Comment by tsawitzki** [comment]
~~By the way, I currently get what I am aiming for, but I have the feeling that it’s dirty and bad practice and could be improved heavily.~~ This is what I have in my jQuery Ajax 'success' callback:

```
if($('#container').length) {
  mixer.destroy();
  setTimeout(function(){
    initMixItUp();
    mixer.forceRefresh();
  }, 1);
}
```

**EDIT:** Actually this fails badly in certain circumstances …

What I am looking for is this logic:

- does the loaded markup contain an element with the ID "container", meaning we loaded a page with items to be mixed-up?
- if so: let "#container" be treated by MixItUp:
- has MixItUp already been instantiated before?
- if so, just remix the items in "#container"
- if not, instantiate MixItUp on "#container"

The problems I always ended up with was either the page/mix-grid not being rendered at all or being rendered with the filters buttons having no effect, respectively no MixItUp event listeners bound to them.

**Comment by patrickkunka** [comment]
Hi @tsawitzki,

I would recommend the following approach with MixItUp 3:

1. When your page loads, instantiate your mixer:

```js
var mixer = mixitup('#container');
```

2. Whenever your ajax page load code is called, always destroy the active mixer first:

```js
if (typeof mixer !== 'undefined') {
   mixer.destroy();
}
```

3. When your ajax has finished and your new page has rendered, always instantiate again:

```js
var mixer = mixitup('#container');
```

You'll probably want to abstract 1 and 3 into a single function that can be called at various points in the  lifecycle of your site, which could also check that the `#container` element exists first. 

MixItUp 3 will never let your instantiate over the top of an active mixer on the same element, so the `isLoaded` has been removed as is no longer neccessary. You will see a console warning if you try to do so. Therefore, if you always just instantiated and never destroyed, it would still work, but the above ensures that no warnings will be fired, and you get a fresh instance each time.

You'll just need to identify the appropriate places in your ajax code to hook into (via callbacks or promises or otherwise). Let me know if that helps.

As a side-note, and for other people reading this, the above code assumes you're working in a single top-level namespace for all your site's JS code (i.e. global variables), which is fine for basic static pages. However, if you are doing stuff like dynamically rendering pages via ajax, you may want to component-ize the reusable parts of your UI. For example - create a "filterable grid" component that manages the instantiation and garbage collection of mixitup, and can be instantiated whenever your newly-rendered view contains the appropriate elements (i.e. a grid). This probably isn't necessary for now, but something to bear in mind for the future. FYI, this is what most UI frameworks like React, Angular etc are doing on some level.

**Comment by shaid85** [comment]
Hi Patrick Kunka, Thank you 
it has save my time. 
`				function my_repeater_show_more() {
					var mixer = mixitup('.gallery_wrap');
					// make ajax request
					jQuery.post(
						my_repeater_ajax_url, {
							// this is the AJAX action we set up in PHP
							'action': 'my_repeater_show_more',
							'post_id': my_repeater_field_post_id,
							'offset': my_repeater_field_offset,
							'nonce': my_repeater_field_nonce
						},
						function (json) {
							// add content to container
							// this ID must match the containter 
							// you want to append content to
							jQuery('.gallery_wrap').append(json['content']);
					/* mixItUp */	


if (typeof mixer !== 'undefined') {
   mixer.destroy();
}


 setInterval(function () {
/* mixItUp */	
var mixer = mixitup('.gallery_wrap');

    },500);



							// update offset
							my_repeater_field_offset = json['offset'];
							// see if there is more, if not then hide the more link
							if (!json['more']) {
								// this ID must match the id of the show more link
								jQuery('#my-repeater-show-more-link').css('visibility', 'hidden');
							}
						},
						'json'
					);

	
				}`
