### ISSUE TITLE
Pagination callback?

### ISSUE THREAD

**Issue by mattyd2478** [patrickkunka/mixitup#302]
Great plugins and all working fine but I just wondered if there was a callback I could tap into after navigating from page to page using the pagination plugin?

**Comment by patrickkunka** [comment]
Hi,

Yes you can use the onMixEnd callback, which is called at the end of any operation including pagination.

If you need to be sure that a page change has occurred (rather than a filter/sort etc), you can store the current page in a variable then compare it with the active page of the new state sent to the callback, before updating the variable.
