### ISSUE TITLE
Bind the sorting to onchange event

### ISSUE THREAD

**Issue by virtualLast** [patrickkunka/mixitup#304]
```js
const ltohFilter = document.querySelector('#filter-ltoh');

if (ltohFilter) {
    function changeFilter() {
        var mixer = mixitup('.container');
	    
        mixer.sort(ltohFilter.value);
        console.log('we change the filter');
    }
			
    ltohFilter.addEventListener('change', changeFilter);
}
```

I am using the above code to try and get a select element to update the sorting, which is bound to a click event by default. I am getting an error saying that mixitup has all ready been instantiated and I need to reference it. How do I do that?

ps. apologies for the awful message, but my email was garbled and I've written this really quickly

**Comment by patrickkunka** [comment]
Hi Mike,

It's just a warning (not an error) so you can ignore it if you like, but it's there because it indicates you're probably doing something wrong or misunderstanding the API. 

In this case - if possible - it's better to create a single mixer instance for the whole session, which you then store as a reference in the `mixer` variable for later use (i.e. programmatic sorting via the API).

I would recommend slightly restructuring your code to the following:

```js
// When your JavaScript initialises, instantiate mixitup and store as a reference:

const mixer = mixitup('.container');
const ltohFilter = document.querySelector('#filter-ltoh');

function changeFilter() {
    mixer.sort(ltohFilter.value);
}

// If the select element exists, bind your change handler:

if (ltohFilter) {	
    ltohFilter.addEventListener('change', changeFilter);
}
```

In your existing code, you were essentially trying to instantiate a new mixer (by calling the `mixitup()` factory function) on every change event. This is why the warning is thrown, because you should only need to do this once.

In the above code, we create one mixer for the session, and interact with it via the API on the change event.

**Comment by virtualLast** [comment]
thanks for getting back to me, not sure if this is a spanner to the works or not....but,
the mixitup library is all ready initialised because we are using the data attributes tags to filter is there a way to reference that existing instance? My understanding of the code above is that we'll be initialising another mixitup instance just to set up this new filtering feature

**Comment by patrickkunka** [comment]
You must be instantiating MixItUp somewhere in your code in order for it to work, so yes you should be able to reference that existing instance.

Happy to take at your code/page if you have a link.

**Comment by virtualLast** [comment]
Ah dude! thanks got it working
