### ISSUE TITLE
callback: onMixEnd onMixLoad

### ISSUE THREAD

**Issue by jimblue** [patrickkunka/mixitup#308]
Hi @patrickkunka !

I'm using **FitText.js** to adjust fontsize dynamically.
It's a very nice way to adapt font-size, but I can make it work properly with **Mixitup**.

I think it's because **FitText.js** needs the with of the text wrapper to calculate the font-size. But on document ready **Mixitup** is not fully loaded and element to calculate with doesn't exist.

I guess the solution would be to instantiate **FitText.js** once **Mixitup** is full loaded, but there is not such callback.

Here is a gist of my code:

[Mixitup Responsive Font Raw](https://gist.github.com/jmbelloteau/dc503fed4a82fce39543ee0309a02197)

If you have any suggestion I would be really grateful 😃  !

**Comment by jimblue** [comment]
Guys, any hint for this problem?

**Comment by patrickkunka** [comment]
Hi @jimblue 

There is no load callback for MixItup 3, because v3 instantiates synchronously.

Therefore, you can call your code directly after you call the `mixitup()` factory function, in the same callstack.

```js
var mixer = mixitup(container, config);

// MixItUp is ready, execute your other code...
```

MixItUp does not dictate or make any changes to the styling of your elements on instantiation, so I'm not sure what you mean by 'fully loaded'. One of the main purposes of MixItUp is to allow you to use standard responsive CSS techniques such as percentages and breakpoints, so your use of FitText.js should not be dependent on MixItUp.

Happy to look into this more if you can provide a link or JsFiddle demonstrating the problem.

**Comment by jimblue** [comment]
Hi @patrickkunka,

I'm using fit **Texttext.js** but I forget to tell you I'm using **[Lazysizes.js](https://github.com/aFarkas/lazysizes)** too.

And I have good reason to think my problem was finally due too **Lazysizes.js** (sorry...)

Without the image loaded element with are equal to zero and **Fittext.js** can't calculate the font size properly.

I've just found a way to instantiate **Fittext.js** once all lazy images of **Mixitup** are loaded.

I'm pretty sure it can't' be done in a better way but it's working for now 😄 !

Thanks for your help!!
