### ISSUE TITLE
Can't get pagination plugin to work in angular directive

### ISSUE THREAD

**Issue by kylegillen** [patrickkunka/mixitup#309]
Hi. Fantastic plugin. It's been great since v1. Thanks for making it!

I just purchased the pagination plugin and am trying to get it to work within my angular directive.
The only I seem to be able to get the initial mixitup plugin to run however is if I use it this way, in the directive's link function or controller:

```
angular.element(document).ready(function () {
    angular.element(element).mixItUp({
        pagination: {
            limit: 3
       },
       animation: {
           nudge: false
       }
    });
})
```

The method shown in the demo (`var mixer = containerEl.mixitup()`) doesn't seem to work in my project. Further more if I use querySelector to try and initialize, that also doesn't work. It only seems to initialize via jquery (JqLite in this example), and it must be wrapped in the `document.ready` funcion, a `$timeout` doesn't work.  Perhaps it's due to my content being dynamic? (using ng-repeat).

Regardless though, pagination doesn't work using the method above. Mixitup does, but not pagination.

I'm using version 3.1.9 of mixitup & 3.2.0 of pagination.

I figured I'd ask because I can't seem to figure it out, and I thought this would be the best forum.

Thanks in advance!

**Comment by patrickkunka** [comment]
Hi Kyle,

I'm not too familiar with Angular i'm afraid.

I can see you're using the legacy jQuery API in the example. What happens when you try to use the v3 vanilla JS API?

You should be able to do this (the syntax you mentioned above isn't quite right):

```js
var mixer = mixitup(element, {
    pagination: {
        limit: 3
    },
    animation: {
        nudge: false
    }
});
```

I'm not sure where you're calling the above code relative to the lifecycle of your directive, but i'm guessing there should be a way of waiting until the DOM is ready/available within the directive (equivalent to React's `componentDidMount`) so binding to document ready shouldn't be necessary.

As long as `element` is a valid element reference, and it exists within the visible DOM at that point, you should be fine, but as I said I'm not too familiar with Angular, so may not be the best person to help with this one. I guess the important thing to say though, is that there is no fundamental incompatibility, so it should in theory work.

**Comment by patrickkunka** [comment]
Closing for now. Please let me know if you want me to reopen.
