### ISSUE TITLE
"Force sort" functionality

### ISSUE THREAD

**Issue by nathanhornby** [patrickkunka/mixitup#311]
I have a list of elements that can be marked as 'complete'.  I'm using the sort functionality to locate complete items at the bottom of the list. This works fine as a default state, or if I switch between sorting methods - but if an item becomes complete and I trigger the currently active sort() again nothing happens. I hoped that forceRefresh() would get around this, but it doesn't seem to re-sort the list based on the set up config.

How can I ask a mixitup instance to *re-sort* the list?

**Comment by patrickkunka** [comment]
Hi Nathan,

Sorry for the delay in response as I've been on vacation.

MixItUp has some internal optimizations to ensure redundant operations are avoided, one of these involves checking if the newly requested sort command is the same as the currently active one, and if so - skips the operation for efficiency. This is probably the cause of what you're experiencing.

I will have a think about adding a `forceSort` configuration option because this sounds like a valid use case, but in the meantime, the only solution I can think of would be to destroy and reinstantiate your mixer every time an item in the list is completed. You could either reinstantiate with `load.sort` set to your desired order, or call the `.sort()` API method after instantiation (if you want the animation).

Let me know if this works, or if you need additional guidance on how to do the above.

**Comment by nathanhornby** [comment]
Hi @patrickkunka thanks for getting back!

Makes sense, and thank you for considering the new feature.

I'll give that a try, I have a suspicion that it will lack the transitional slickness I require, but I may be wrong!

**Comment by patrickkunka** [comment]
Hi Nathan - if you reinstantiate, then call .sort() via the API, you should get the transition.

**Comment by nathanhornby** [comment]
My issue is that I call in a big data-set and then 'filter' it into 'tabs'. So when I destroy the mixitup instance my page is going to crumble into a mess before mixitup reinitialises and then sorts. I don't think it would be a smooth transition. I'll experiment though.

**Comment by patrickkunka** [comment]
OK - perhaps you could instantiate with the exact same filter state as when destroyed? When you destroy, the DOM will not be manipulated by default, so it should be static until you sort.

**Comment by nathanhornby** [comment]
Thanks, good to know! I may have more success than expected. I'll report back when I circle back to that issue!

**Comment by jcwchriswalker** [comment]
Hi Patrick- I am in the same situation as Nathan where my dashboard items are refreshed every X seconds. The filtering attribute works wonderfully where I see the items appear/hide based on the filter attributes after the refresh. However like you said previously, they don't re-sort. A forceSort() on the updated filtered view would be great. I agree with Nathan about the 'slickness' of the items moving around.  I have not tried the suggestion you gave Nathan about destroy() then reinstaniate because if you are considering this forceSort() soon, I'll just wait.

**Comment by jcwchriswalker** [comment]
I decided to try Patrick's suggestion of doing a mixer.destroy() and then rebuild the mixer using both the filter and sort values saved from the previous instance of the mixer:

1.  mixer.destroy();  // Do not delete the mixer DOM elements in the mix container
2. create a new config Object with the load: object just setting the filter selector string
3. call mixitup(container,newConfigObj);
4. call mixer.sort(savedsortexpression)

With a testcase of 25 DOM elements in the container, I see reasonable performance as well as the animation when sorting. Since I did not delete any DOM elements in the destroy() and reload, there was no 'page crumble into a mess' that I too feared would happen.  Thanks!

**Comment by patrickkunka** [comment]
Hi guys,

I've just pushed [v3.1.12](https://github.com/patrickkunka/mixitup/releases/tag/v3.1.12), which now includes a `behavior.liveSort` configuration option that you can toggle on to achieve this.

Please let me know if it works for you as intended.

Docs are here under `mixitup.Config.behavior` -> `liveSort`:

https://www.kunkalabs.com/mixitup/docs/configuration-object/

**Comment by jcwchriswalker** [comment]
Verified with setting behavior{liveSort : true} and behavior{liveSort : false}. Thanks! Interesting that you chose the spelling 'behavior' instead of 'behaviour'...  ;)

**Comment by patrickkunka** [comment]
Great! Haha well observed. I try to write APIs that are as easy to use as possible for the most number of people. Unfortunately that means sacrificing British English sometimes :)

**Comment by VladimirBazhenov** [comment]
You can use this trick:

// two call is important for clearing the state of sorting
window.mixer.sort().then(function (){
    window.mixer.sort('price:asc'); 
});
