### ISSUE TITLE
Custom sorting with an array

### ISSUE THREAD

**Issue by robjonesdev87** [patrickkunka/mixitup#319]
Hi,

Is it possible to sort on load using an array of id's like [35,33,34]?

If so, would you be able to give a full example as I'm unable to find any docs on this.

Thanks!

**Comment by patrickkunka** [comment]
Hi @irtehbom,

You can sort by an array, but the array you provide to `load.sort` or the `.sort()` API method must be an array of target elements, which you would need to build yourself beforehand using custom JavaScript.

For example:

``` html
<div class="container">
    <div class="mix" data-id="33"> ... </div>
    <div class="mix" data-id="34"> ... </div>
    <div class="mix" data-id="35"> ... </div>
</div>
```

``` js
const ids = [35, 33, 34];
const targets = ids.map(id => document.querySelector('[data-id="' + id + '"]'));

const mixer = mixitup('.container', {
    load: {
        sort: targets
    }
});
```

Using the array of IDs, we query the DOM for elements matching those IDs, in the desired order, pushing the returned target elements into an array `targets`.

When we instantiate MixItUp, we pass that array of targets to the `load.sort` config option.

Because we have used a data attribute to contain the ID in the markup, if we want to return to standard numerical ordering, we can use `id` as a sort order:

`mixer.sort('id:asc')`

Hope that helps.
