### ISSUE TITLE
Using a select instead of buttons for filtering

### ISSUE THREAD

**Issue by tyssen** [patrickkunka/mixitup#323]
Hi, great library,

I'm wanting to use a select element instead of buttons for filtering and based on [this issue](https://github.com/patrickkunka/mixitup/issues/304), I've come up with 

	var mixer = mixitup('.filter-list');
	var filter = document.querySelector('#filter');

	function changeFilter() {
	  mixer.sort(filter.value);
	}

	if (filter) {
	  filter.addEventListener('change', changeFilter);
	}

with the select that looks like 

    <select id="filter">
      <option value="all">All</option>
      <option value=".book">Books</option>
      <option value=".gift">Gifts</option>
    </select>

In a grid of 5 rows x 4 columns, when I select any of the options it's swapping row 1 col 1 with row 3 col 3 but not filtering correctly.

In the console, I'm getting: 

> [MixItUp] WARNING: The requested sorting data attribute "data-gift" was not present on one or more target elements which may product unexpected sort output

Currently my list has `book` and `gift` classes on the items. I tried with data attributes instead and got the same warning.

Any pointers as to where I'm going wrong would be greatly appreciated.

**Comment by patrickkunka** [comment]
Hi @tyssen,

In the example you based this on, the author was actually attempting to "sort" the container, not filter it, hence why `mixer.sort()` API method was used.

A lot of people get these two terms confused and use them interchangeably, but they are completely different:
- "sorting" = changing the order of items
- "filtering" = hiding and showing items

I'm pretty sure that what you are trying to do is filter, but because you're calling the sort API and don't have the necessary sorting data attributes on your elements you're getting the error above.

Thankfully a very easy fix:

```js
var mixer = mixitup('.filter-list');
var filter = document.querySelector('#filter');

function changeFilter() {
  mixer.filter(filter.value);
}

if (filter) {
  filter.addEventListener('change', changeFilter);
}
```
I've simply changed the `.sort()` for a `.filter()`. Hopefully that should do it.

**Comment by tyssen** [comment]
Yep, that was it, thanks. 👍
