### ISSUE TITLE
Filter buttons

### ISSUE THREAD

**Issue by Alexand3r3** [patrickkunka/mixitup#325]
Hi,
using multifilter extension, it's mandatory use `<form>` and `<fieldset>` html tags for filter button?
Because if I don't use this html tags, on click the reset button don't remove active class on others button filter.

Is possible use another html tags for the multifilter?

Thanks in advance.

**Comment by patrickkunka** [comment]
Hi Alexander,

It is only necessary if you want to take advantage of things like the `<button type="reset">` and `<button type="submit">` in your form UI. This is because MultiFilter uses the browser's native form `reset` and `submit` events internally, and these can only be created within a `<form>` element.

If you just want filter and toggle buttons, you can use whatever elements you like.

**Comment by Alexand3r3** [comment]
If I want create custom reset button to clear all selected filters without using `<button type="reset">`?

**Comment by patrickkunka** [comment]
If you are just using plain MixItUp, you can use a filter button with "all" to clear all filters/toggles.
`<button type="button" data-filter="all">Reset</button>`

Unfortunately, if you are using the MultiFilter extension, this will not work because MultiFilter UI is _uni-directional not bi-directional_. In other words, it cannot infer the state of all possible UI from just a selector string. So you must use `<button type="reset">Reset</button>` to ensure that the UI is firstly reset and then re-parsed.

Is there a reason you can't use a `<form>`?

**Comment by Alexand3r3** [comment]
Because the plugin is working on ASP.NET based server which doesn't accept a `<form>` tag. This is the reason for that I can't use the `<form>` tag.

**Comment by patrickkunka** [comment]
Ah I see.

In that case, you can write some custom JS to do the same thing via the MultiFilter `setFilterGroupSelectors` API. It's not ideal but it should work.

##### HTML
```html
<div>
  <div data-filter-group="color">
    <!-- color controls -->
  </div>

  <div data-filter-group="size">
    <!-- size controls -->
  </div>

  <button type="button" id="reset-filters">Reset</button>
</div>

```
>  Non-form filter UI with "named" filter groups

#### JS
```js
var resetBtn = document.getElementById('reset-filters');

var mixer = mixitup(container, {
    multifilter: {
        enable: true
    }
});

resetBtn.addEventListener('click', function() {
    // 1. Manually deactivate all active filter UI
    // E.g. remove active classes, uncheck radios/checkboxes, clear the
    // values on text inputs etc

    // 2. Go through each named group and set active filters to an empty array

    mixer.setFilterGroupSelectors('color', []);
    mixer.setFilterGroupSelectors('size', []);

    // 3. Reparse the filter groups

    mixer.parseFilterGroups();
});
```
> Custom click handler attached to fake reset button

**Comment by Alexand3r3** [comment]
Oh great!!

It's works fine!!!

Thanks very much!! I love more this mixitup!! :D

**Comment by websandesign** [comment]
Hi. Why your website is not working? I really need documentation for Mixitup. Thanks!
