### ISSUE TITLE
Force rerender

### ISSUE THREAD

**Issue by OpticNectar** [patrickkunka/mixitup#328]
Is there a way to force items to rerender? I have a button on my page that changes the template used in the render function and nothing seems to make the items rerender, even `forceRefresh`. I'm using the dataset api and i'm using load for the initial values if that helps.

**Comment by patrickkunka** [comment]
Hi there,

When using dataset, re-renders are only triggered when:
1. `data.dirtyCheck` is set to `true`
2. A target's underlying data has changed
3. The .dataset() method is called.

I think your use case is valid though, and perhaps I need to add an additional public API `.render()` method could be added to trigger arbitrary re-rendering of all targets on demand. Does this sound like it would work for you?

In the mean time, I think I have a pretty good workaround solution for you.

With dirty checking enabled, you could trigger a re-render by changing some arbitrary property on each item in your data and then calling `.dataset()`. 

For example, you could add a `template` prop to all your items data.

Initialise items with:
```
{
  id: 1,
  template: 'TEMPLATE_A',
}
```

Then, iterate through all items and change change to:
```
{
  id: 1,
  template: 'TEMPLATE_B'
}
```
Then update your render function appropriately, and then call:
`mixer.dataset([...])`

MixItUp will see that the data of each item has changed, and call your render function.

Rather than manually changing the render function however, you could have some logic inside a single render function which dictates which template should be used, and render different markup for each condition. This way you would be driving the whole operation from the data, rather than just using the data to fake trigger the re-rendering.

```js
var mixer = mixitup(container, {
    ...,
    render: {
        target: data => {
            if (data.template === 'TEMPLATE_A') {
                return `<div class="foo">...</div>`;
            } else if (data.template === 'TEMPLATE_B') {
                return `<div class="bar">...</div>`;
            }
        }
    }
}
```

I hope that makes sense!

**Comment by OpticNectar** [comment]
Yeah a render method would be perfect. For now I ended up doing this:

```
this.grid.dataset([]).then(function() {
    that.grid.destroy();
    var gridElementMix = document.querySelector('[data-ref="container"]');
    that.grid = mixitup(gridElementMix, {
        data: {
            uidKey: 'id',
            dirtyCheck: true
        },
        render: {
            target: function(item) {
                return that.render(item);
            }
        },
        selectors: {
            target: '.grid-item'
        }
    });
    that.grid.dataset(that.items);
});
```

I am using the code inside an object and storing the items myself since I have to handle pagination (the plugin doesn't keep track of previous items when you set the dataset), so I ended up just using the code I have above. It works for now. If/when there is a render method i'll update it.

**Comment by patrickkunka** [comment]
I've decided not to add this feature in the end because I feel it breaks the dataset pattern, which is that re-rendering should only occur in response to data changes, and every change must go through the `dataset()` method.

So, as I suggested above, rather than the button on your page changing the template, it should change the underlying data of your targets, and your template should contain the necessary conditions to produce the two desired HTML outputs.

If you have a strong reason why you think this isn't sufficient, I'd be happy to hear it but I'm going to close for now.

**Comment by OpticNectar** [comment]
I understand where you are coming from, but at the same time, data is data and templates are templates. I think it is counterintuitive to have to change the template in the code and then have to modify each element in the dataset just to tell the script to re-render. Nothing in the data has changed at all, just the template used to show it, so why should I have to modify the template?

**Comment by patrickkunka** [comment]
Yeah I do think that's a totally reasonable argument, and I can see the redundancy/overhead of having to do that additional mapping across a large dataset. Let me give it some additional thought to see if there's a solution that's more inkeeping with the functional pattern.

**Comment by OpticNectar** [comment]
Sounds good. Also, you have to think that if I did what you said and modified all my data to have a template variable so they would be re-rendered and then the user sorted or something of that nature, now I have data that has the template variable and some that doesn't. This quickly becomes messy and it's also changing data for the sake of the template/scripting, which are two different things and goes against what an API is. You even mention yourself in the docs for preloaded data  should be identical to what's rendered so why should it then be modified and different from what comes back from the server in future requests?

**Comment by patrickkunka** [comment]
Have now added a `forceRender()` method in https://github.com/patrickkunka/mixitup/releases/tag/v3.2.1

Please let me know if this is working as intended. Docs are here: https://www.kunkalabs.com/mixitup/docs/api-methods/

Enjoy!

**Comment by OpticNectar** [comment]
Perfect!! Thanks!! That got rid of about 25 lines of code. :)
