### ISSUE TITLE
Uncaught TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by nevonevo** [patrickkunka/mixitup#330]
hi i try to use mixitup plug in for my php peoject and i get this error when i am using html table for my data.
```
Uncaught TypeError: Cannot read property 'filter' of undefined
    at HTMLTableRowElement.<anonymous> (mixitup.min.js:16)
    at Function.each (jquery-3.2.1.js:362)
    at jQuery.fn.init.each (jquery-3.2.1.js:157)
    at jQuery.fn.init.t.fn.mixItUp (mixitup.min.js:16)
    at filter.js:110
```

```js
	$(".arama_box input[type='search']").keyup(function(){
	  	// Delay function invoked to make sure user stopped typing
	  	delay(function(){
	    	inputText = $(".arama_box input[type='search']").val().toLowerCase();
	   		// Check to see if input field is empty
	    	if ((inputText.length) > 0) {            
	      		$('.mix').each(function() {
		        	var $this = $(this);
		        
		        	// add item to be filtered out if input text matches items inside the title   
		        	if($this.attr('class').toLowerCase().match(inputText)) {
		          		$matching = $matching.add(this);
		        	} else {
		          		// removes any previously matched item
		          		$matching = $matching.not(this);
		        	}
	      		});
	      		$('table tr.srchfilter').mixItUp('filter', $matching);
	    	} else {
	      		// resets the filter to show all item if input is empty
	      		$('table tr.srchfilter').mixItUp('filter', 'all');
	    	}
	  	}, 200 );
	});
```

i really dont know why i get this issue. please help me. thanks and best regards.

**Comment by patrickkunka** [comment]
Hi Nevo,

Thanks for the information.

Firstly, as you appear to be using MixItUp v2, I would recommend upgrading to MixItUp v3, which fixes various issues and vastly improved performance.

You can find a migration guide here detailing the changes you need to make:

https://www.kunkalabs.com/mixitup/migration-guide/

Secondly, we have a demo here which does exactly what you need, in terms of filtering by text input, so I would recommend replacing your custom jQuery code with the code in this demo:

https://demos.kunkalabs.com/mixitup/filtering-by-text-input/

Finally, when dealing with tables, you need to make sure that the `<tbody>` element is your container, and that the `<tr>` elements are your target elements. This is because in all target elements must be siblings in a MixItUp container.

Also worth noting is that because tables use a different box model from all other HTML elements, MixItUp's animations may not work as expected when filtering or sorting within tables. So if you must use a table, I would recommend disabling animations completely.

I hope that helps.
