### ISSUE TITLE
MixItUp Pagination: Install with Bower? 

### ISSUE THREAD

**Issue by ericanafziger** [patrickkunka/mixitup#331]
I have the latest version of Mix It Up installed as a bower component. I recently purchased the pagination extension. Is there a was to install this as a bower component as well?

**Comment by patrickkunka** [comment]
Hi,

Because the premium extensions are not open source, they are not publicly available via any package manager.

However, if you have a private GitHub or NPM account, you can host your copy of the extension there, and link to it in your `package.json` to automate your build process, and avoid having to check mixitup extensions into your source code.

Using a private GitHub for example, in your `dependencies` or `devDependencies` stanza, add the following:

```
{
  "mixitup-pagination": "git+ssh://git@github.com:yourorganization/mixitup-pagination.git",
  ...
}
```

Then when you run `npm install`, and provided your machine is authentication via SSH, NPM will install the extension and make it available to your project.

**Comment by ericanafziger** [comment]
Thanks for the quick answer Patrick. Do you have any more advanced examples with pagination on CodePen or GitHub? I’m having some trouble integrating into the CMS I’m working with. I’m guessing probably not since it isn’t open source, but I thought I would check just in case.

Thanks!

Erica Nafziger / UX Specialist
W: 971-352-4916
Sq1
sq1.com

BE BULLISH AND WIN

**Comment by patrickkunka** [comment]
Hi Erica,

We currently just have the demos which are included in the source code, but if you let me know exactly what you're trying to do I can try to help.
