### ISSUE TITLE
grid columns animation on resize?

### ISSUE THREAD

**Issue by neuropass** [patrickkunka/mixitup#334]
Hi,
not really an issue , but maybe you can point me in the right direction.
Looking at this example:
https://demos.kunkalabs.com/mixitup/grid-columns/

How can I have the same smooth animation as when you press "shuffle" when the page is resized?

Thanks again I love this plugin.

**Comment by patrickkunka** [comment]
Hello,

MixItUp was designed to have no JavaScript overhead on resize or layout paint, so this feature would go against the basic philosophy of MixItUp which is to use native CSS layout.

When you see this sort of behavior in libraries such as Isotope, it's a really side effect or bi-product of the fact that they are using JavaScript-based absolute positioning for layout, rather than native CSS.

Hope that makes sense.
