### ISSUE TITLE
sorting only specific filters

### ISSUE THREAD

**Issue by nandoblanco** [patrickkunka/mixitup#339]
Is it possible? 

Example: the Admin filter would show the cards in the order they are in on the page but the Faculty filter would show the cards in alphabetical order. 

Thanks in advance!

**Comment by patrickkunka** [comment]
Yes this is possible.

Control buttons may have both `data-sort` and `data-filter` attributes present.

This is the equivalent of using the `.multimix()` API method.

**Comment by nandoblanco** [comment]
That's what I thought but adding data-sort to my filter links seems to be breaking it :(

https://xxx/directory/index.html

Can you have a look and tell me where I'm going wrong please?

Thanks in advance!

**Comment by patrickkunka** [comment]
Hi, I've taken a look at your page and the problem is caused by your markup structure.

Within your mixitup container, you have a series of cards with the class `mix` on them. These are your "targets", which is correct.

However, within each card, you have another "panel" element which also has the class `mix` on it. MixItUp is indexing both sets of elements (the targets, and their children) as targets, and when it iterates through the "panels", it can't find the `data-lname` attribute, and the error is thrown.

You should be able to just remove the `mix` class from the inner elements and that will fix it.

**Comment by nandoblanco** [comment]
so... yeah that was it lol 

I did that bc I had an issue with match height script I was using but it's fixed now as well...

thanks so much!
