### ISSUE TITLE
force sort via URL hash?

### ISSUE THREAD

**Issue by nandoblanco** [patrickkunka/mixitup#341]
In connection to my other issue, I now have filter links that filter and sort as needed. 

Different filters sort different ways, when on the page it works fine. When I link out to the page, it filters fine but obviously doesn't sort. 

How would I use the hash/filter in the URL to sort accordingly?

**Comment by patrickkunka** [comment]
Hi the pattern is exactly the same as this demo:

http://patrickkunka.dev/mixitup/demos/filtering-by-url/

However instead of a single hash `#blue`, you need to construct a hash segment with additional information in it:

For example: `#filter=blue&sort=default:asc`

You would need to implement code to serialise/deserialise that hash segment when writing and reading from it, but as with the filtering, you interface with MixItUp using the `load.filter` and `load.sort` configuration options when instantiating your mixer, passing in the values parsed in from the hash.
