### ISSUE TITLE
Advanced filtering

### ISSUE THREAD

**Issue by daniel-nemeth** [patrickkunka/mixitup#342]
Hi! First: Great job!

I have a page using mixitup library with filtering via buttons.

Now on filtering I want to check how many items are in the result. If there are less then 12 items, it should add random items which are normally not shown by the filter and prepend them to the filtered items.

Is it possible to achieve this behaviour?

**Comment by patrickkunka** [comment]
Hi Daniel,

You can do this by interfacing with MixItUp via its API rather than the standard controls.

Firstly, you'd need to obtain an array of all targets element using `container.querySelectorAll('.mix')` or similar, or you can just pull this out of the MixItUp state object after instantiation.

You would then iterate through this list calling `target.matches('.my-category')` on each target element to check if it matches your filter, and if so, pushing it into a new array.

If the length of this new array is less than 12, you would then iterate through the targets array again at randomized indexes, pushing each item into the new array if its not already there, until you have 12 items.

You'll then have an array of 12 targets elements which you can pass to MixItUp.

`mixer.filter(myFilterArray)`

You'll want to disable the default controls set up your own click handlers to call the above functionality instead.

Hope that makes sense.
