### ISSUE TITLE
Error on any page other than the one mixitup is on

### ISSUE THREAD

**Issue by darrenbachan** [patrickkunka/mixitup#343]
On my homepage I have mixitup working using this:

```js
var containerEl = document.querySelector('.gallery-container');
var mixer = mixitup(containerEl, {
         selectors: {
             control: '[data-mixitup-control]'
         },
         load: {
             filter: '.engagement-ceremony'
         }
});
```
It works fine, but the moment I go to another page I'm getting this error in console: 

```
Uncaught Error: [MixItUp] An invalid selector or element reference was passed to the mixitup factory function
```
and it's causing my other js on the page to break.

I thought I'd try this instead to see what happens:

```js
var mixer = mixitup('.gallery-container', {
         selectors: {
             control: '[data-mixitup-control]'
         },
         load: {
             filter: '.engagement-ceremony'
         }
});
```

But then I got this error: 

```
Uncaught Error: [MixItUp] The provided selector yielded no container element.
```

**Comment by patrickkunka** [comment]
Hi,

Both errors are caused by the same issue. You are trying to instantiate MixItUp on pages where the `'.gallery-container'` does not exist in the DOM. In the first case, your call to `document.querySelector()` returned `null`, which is not a valid selector or element. In the second case, MixItUp does the same thing internally with your provided string, but again nothing was found.

This indicates that you are running the instantiation code above in circumstances where it should not be run.

If you have no choice but to run the same JS on every page/view of your site, you can wrap your MixItUp code in a conditional check, to prevent instantiation when `'.gallery-container'` does not exist.

For example:

```js
var containerEl = document.querySelector('.gallery-container');
var mixer;

if (containerEl) {
    mixer = mixitup(containerEl, {
         selectors: {
             control: '[data-mixitup-control]'
         },
         load: {
             filter: '.engagement-ceremony'
         }
    });
}
```

**Comment by darrenbachan** [comment]
Yeah, I'm using wordpress so my js file is loaded on each page. I ended up loading it conditionally based on the page to get it to work without errors, but I'll give your fix a shot.
