### ISSUE TITLE
Multiple filters on load breaks active class on buttons?

### ISSUE THREAD

**Issue by mattmesker** [patrickkunka/mixitup#344]
I'm initializing MixItUp with a compound selector string (which works correctly), but the corresponding buttons don't receive the "mixitup-control-active" class. It works fine with a single filter, but any combination of more than one doesn't work.

Is there a way to set the active classes to the correct data-filter objects on load?

I'm using the MultiFilter add-on as well, in case that matters.

Example:

```
var items = $('#items');
var mixer = mixitup(items, {
  load: { 
    filter: '.pizza.tacos',
  }
});
```

**Comment by patrickkunka** [comment]
Hi Matt,

MultiFilter has no way of knowing how to break down compound selectors and apply the active class to the appropriate filter groups.

When using the MultiFilter extension, you'll need to set these filters programmatically manually using the `setFilterGroupsSelectors()` API method described here: https://www.kunkalabs.com/mixitup-multifilter/docs/api-methods/

As mentioned, you need to "name" your filter groups in order to interact with them over the API:

```
<form>
    <fieldset data-filter-group="foods">
        <button type="button" data-filter=".pizza">Pizza</button>
        <button type="button" data-filter=".tacos">Tacos</button>
        ...
    </fieldset>
    ...
</form>
```

Once you have done that, your instantiation should look something like this:

```js
var mixer = mixitup(items);

mixer.setFilterGroupSelectors('foods', ['.pizza', '.tacos']);

mixer.parseFilterGroups(false); // NB: `false` is passed to disable animation on this API call, so that your active filters become instantly activated on instantiation.

```
