### ISSUE TITLE
Multi-Filter Reset problem

### ISSUE THREAD

**Issue by meanmrm** [patrickkunka/mixitup#355]
Hi.
Sometimes the Filter function is hanging and i can't reset the options.
I can't figure out what the problem is.
http://dev.tube-design.ch/kimu/tour_tickets.php
have a look at the filter on top of the list.
Thank you for help.
Best regards

**Comment by patrickkunka** [comment]
Hi @meanmrm,

I've taken a look at your link. The structure of your markup means that certain `transitionend` events are not being picked up from your the target elements, which is hanging the animations.

There is second container with ID "ContainerList" nested inside the first one, which MixItUp is instantiated on. If you remove this second container, everything seems to work fine. I'm not sure if this is intentional or a bug in your HTML rendering.

IDs must be unique and all MixItUp targets must be siblings. By having MixItUp targets nested inside a container within the top-level container, animation events can not be picked up correctly which is causing this issue.

Hope that helps.
