### ISSUE TITLE
Calling paginate with a page number in string format / page stats issues

### ISSUE THREAD

**Issue by Kwapi** [patrickkunka/mixitup#359]
I noticed that if for any reason the new pagination limit set using `mixer.paginate()' is a string (which happens quite often with jQuery's val() function) the endPageAt variable in the pagination stats will not be updated properly. 

It's simple to fix it by making sure that the value passed is actually a number but perhaps an additional parseInt() somewhere in the mixitup pagination code when setting a new limit wouldn't be a bad idea?

**Comment by patrickkunka** [comment]
It's a bit more difficult than that because the `.paginate()` API method is very flexible. For example, all of the following calls are valid:

```js
.paginate(1);

.paginate('next');

.paginate({
   page: 3,
   limit: 10
});

.paginate(anchorElement);
```

Therefore a blanket `parseInt()` won't work. I could call parseInt and then check for `isNaN`, but then that's just another layer of duck typing that would have to be applied to all input types, on top what's already there. So I think it's probably best if the consumer just validates their input first.

EDIT: Oops just checked and I do already do a combination of `parseInt` and `isNaN` in the code, which I guess is why you are able to change the page as expected with a string. In that case, there is a separate issue related to updating the stats which I will look in to!

**Comment by patrickkunka** [comment]
I finally got around to looking into this, but I was unable to recreate any issue relating to sending a number in string form to the `.paginate()` method. The values of the resulting page stats all appeared to be correct.

I will close for now, but if this is still an issue, or you have specific steps to recreate, please let me know and I will reopen.
