### ISSUE TITLE
MultiFilter controls do not reflect active state when calling .filter() API method

### ISSUE THREAD

**Issue by mcmanimie** [patrickkunka/mixitup#362]
I notice if I apply a filter using the load parameter on initialization, the corresponding filter button class will get set as active (awesome), but when I call mixer.filter I see no such action.  Just wondering if that's expected behavior.

**Comment by patrickkunka** [comment]
Hello,

This is not the expected behaviour. If you are just using the MixItUp core then your controls are two-way bound and should stay in sync with any API calls. So it sounds like the may be an issue with your code.

If you are using the the multi filter extension then controls are one-way bound and require a seperate API call to programmatically activate them.

**Comment by mcmanimie** [comment]
Ah, I am using the multifilter, yes. No problem.  As noted, just wasn't 100% sure considering it did work 2-way on load but not on the filter() call.

**Comment by patrickkunka** [comment]
Ah ok - if you want to programmatically filter and have your groups update, you can use the `setFilterGroupSelectors()` API method, which will in turn call `.filter()` internally. More information is available in the MultiFilter API docs.

It has to be done this way when using the extension, as there is no way of knowing how to break up a given arbitrary selector into the desired groups.

**Comment by mcmanimie** [comment]
Brilliant Patrick, exactly what I was looking for.  Works like a charm.  Your library kicks-ass btw.
