### ISSUE TITLE
[MultiFilter] Set filters on load

### ISSUE THREAD

**Issue by Kwapi** [patrickkunka/mixitup#364]
I'm aware of the `load.filter` configuration object but I found that if I set my filters that way then the multifilter functionality is not 'aware' of what was set i.e. - it won't preserve the load filter when mixing with other filters.

I found a solution that involves `setFilterGroupSelectors()` and `parseFilterGroups()`. This works reasonably well but the caveat is that the filtering (and animation) is done after the mixitup object is loaded and presented on the page. Is there a way to maybe delay the initialisation of the mixitup object until I've se my filter group selectors? Or maybe there's some other approach I could try?

Thanks

**Comment by patrickkunka** [comment]
Hi,

Sounds like you're almost there. You're correct that setting `load.filter` when using MultiFilter will not activate your controls, as MultiFilter controls are one-way bound, unlike normal MixItUp controls which are two-way bound and automatically track the state of your mixer. This is because given a arbitrary compound selector, there is no way to know how to break it up back in to the intended groupings and logic combinations, which is why `setFilterGroupSelectors()` exists.

But as you mentioned, calling `setFilterGroupSelectors()` followed by `parseFilterGroups()` will trigger an filter operation which in this case is redundant, as your mixer has already been filtered on load.

The solution is to use a combination of `load.filter` and `setFilterGroupSelectors()`:

```js
var mixer = mixitup(containerEl, {
    multifilter: {
        enable: true
    },
    load: {
        filter: '.green.circle' // set your initial filters
    }
});

// set the state of your filter groups, to match your `load.filter` selector

mixer.setFilterGroupSelectors('color', '.green');
mixer.setFilterGroupSelectors('shape', '.circle');
```
At this point, there is no need to call `parseFilterGroups()` as your MultiFilter controls are now in sync with the mixer.
