### ISSUE TITLE
Does MixItUp 3 works on IE?

### ISSUE THREAD

**Issue by kristinabressler** [patrickkunka/mixitup#365]
I build a portfolio page with MixItUp 3 in Wordpress. However, a recruiter told me that she cannot see the portfolio on Internet Explorer. Is there any workaround or solution for IE?

**Comment by patrickkunka** [comment]
MixItUp 3 is compatible with IE 8 and above, so I don't think the issue is related to MixItUp, but happy to give some advice if you're new to the wonderful world of IE bug testing.

In general, Internet Explorer usually requires a significant amount of bug testing and workarounds due to its non-standard implementations of JavaScript and CSS (at least up until IE11). What might work fine in Chrome, Safari or Firefox will almost always require some extra work and attention in order to function in Internet Explorer.

I would start by finding out which version of IE the issue has been reported on, and trying to get them the recruiter to send you a screenshot. Then you should try to recreate and understand what the issue is. Is it a JavaScript issue (are there errors in the console?), is it a styling issue (is the layout broken?). If you don't have access to Internet Explorer, there are various tools available (such as BrowserStack) which provide virtual testing instances of IE. Once you know what the issue is you can start searching for a solution.

Also, if this person is using an obsolete version of IE (e.g. anything less than IE 11), it's probably not worth worrying about. You may wish to simply block users on obsolete browsers from accessing your portfolio.
