### ISSUE TITLE
Recommended architecture/design for child filters applying only to one parent

### ISSUE THREAD

**Issue by mcmanimie** [patrickkunka/mixitup#367]
What is the recommended way of handling a set of (child) filters that only apply in the event a specific parent is active?  So, for example, I have three main filters: Cars, Trucks, and Bikes.  But under Trucks I wanted to provide the user an additional option of, say: SUV or Pickup.  

If Trucks is selected and the user adds SUV, all is well, but I need to ensure that once a user clicks over to Cars or Bikes, all Trucks child filters are immediately and seamlessly cleared in one nice mixitup operation. 

Manually triggering a click on the reset button for that child group seems sloppy and will seemingly call two refreshes.     

I do have the multifilter library as well.

**Comment by patrickkunka** [comment]
Hi @mcmanimie,

This kind of custom filtering interface differs heavily from project to project, which is why such functionality is not included in MixItUp. Instead, various flexible APIs are exposed allowing you to build highly custom filtering UI which integrates with it MixItUp.

When using MultiFilter, you can use the `setFilterGroupSelectors()` API to set or unset selectors to a specific group. For example, the following would clear all filters for the "Trucks" group:

```js
mixer.setFilterGroupSelectors('trucks', '');
```

This will also update the UI of the group, deactivating or unchecking any selected filters.

Once you've done this, you'll need to call the `mixer.parseFilterGroups()` API method to trigger a filter operation reflective of the updated selection.

```js
mixer.setFilterGroupSelectors('trucks', '');

mixer.parseFilterGroups();
```

However, you mentioned you want to do this when a use "clicks over" to another group. Currently the parsing the new selection, plus the deselection above would trigger two operations, but we want to do it in one. We can set up our mixer so that it doesn't automatically filter whenever a change to a multifilter group occurs. In the config, set the `multifilter.parseOn` option to `'submit'` (not the default `'change'`). This way we can only trigger filter operations on demand, rather than on change.

```js
var mixer = mixitup(containerEl, {
    multifilter: {
        enable: true,
        parseOn: 'submit'
    }
});
```

You'll now want to set up our own `'click'` (or `'change'` if you're using checkboxes or selects) event handler on your multifilter form UI to intercept changes to the filters.

```js
multifilterForm = document.querySelector('.multifilter-form');

function handleFormClick(e) {
    var deactivatedGroupName = ...

    // Custom code here to find out what was clicked and
    // which group (if any) should be deactivated

    if (deactivatedGroupName) {    
        // If a group should be deactivated, clear its active selectors

        mixer.setFilterGroupSelectors(deactivatedGroupName, '');
    }

    // Create the appropriate selector and trigger a filter operation

    mixer.parseFilterGroups();
}

multiFilterForm.addEventListener('click', handleFormClick);
```

I hope that helps

**Comment by mcmanimie** [comment]
Patrick, that's fantastic, man. I really appreciate the helpful insight.

**Comment by mcmanimie** [comment]
Any idea why when I call this upon "clicking off" it would effectively deactivate that control group for the remainder of the session?  It works as intended initially (clears subfilters, run filter), but then anytime I click that control group moving forward it has no effect on the grid.  

I see mixitup-control-active being applied to the control but the grid doesn't update.  No errors in the console. 

Edit: Seems the issue is related to the fact that they are data-toggle controls.

```
mixer.setFilterGroupSelectors('trucks', '');
mixer.parseFilterGroups();
```

**Comment by patrickkunka** [comment]
Would it be possible to share a link to your project?

**Comment by mcmanimie** [comment]
FYI - I had to switch the filters back to filters (from toggles) in the demo. I'll try to set them back this weekend.

<img width="625" alt="ss" src="https://user-images.githubusercontent.com/8271952/31525240-cf3c3b66-af8c-11e7-8669-dd7f5b93e114.png">

**Comment by mcmanimie** [comment]
Hey Patrick, ever have a chance to take a look?  I restored those toggle filters.  As soon as that clearPlasticFilters() routine runs once, it seemingly "de-links" it from filter actions on the grid (even though the 'mixitup-control-active' class is applied to the toggle filter control.

**Comment by mcmanimie** [comment]
Nevermind, went a different direction with these filters.  Not using toggle.

**Comment by patrickkunka** [comment]
OK apologies for lack of response, but will close if all OK now. Let me know if you want me to reopen.
