### ISSUE TITLE
Collapsing / disappearing page content on pagination

### ISSUE THREAD

**Issue by Kwapi** [patrickkunka/mixitup#369]
When switching between the first and second page of my news section the whole page seems to disappear/collapse for a split second. I tried adding `min-width` with pixel values to both the mixitup container and the parent div but to no avail.

Here's the video of the issue:
[Google drive video link](https://drive.google.com/open?id=0ByCOhROBhow9UHNmTWk5S2hRUk0)

and the link to the [live website](http://aurora-network.global/news/)

I'm using customised selectors for mixitup. The container is `[data-filter-results]` and targets are `[data-filter-item]`.

**Comment by patrickkunka** [comment]
Hi @Kwapi - you need to add `overflow: hidden` to your MixItUp container (the element with selector `[data-filter-results]`.

This issue is due to the height of your document changing during a MixItUp operation. This is often an issue when a MixItUp operation results in the document height becoming smaller than the viewport.

Even though your container is shrinking, the height of its content (your targets) is still dictating the height of the overall document, which means we don't get a smooth resize - just an abrupt jump at the end of the animation as the targets are finally switched to `display: none`.

By adding `overflow: hidden` to the container, we can ensure that only the height of the container can affect the height of the document, and we then get a smooth document resize on page change and filter.

**Comment by Kwapi** [comment]
@patrickkunka  you're a star, thanks!
