### ISSUE TITLE
Mixitup huge size

### ISSUE THREAD

**Issue by jimblue** [patrickkunka/mixitup#370]
Hi @patrickkunka !

First thanks for the very nice `Mixitup`... I'm using it on two websites.
I'm mostly happy with it... I only have one bad review which is the huge size of `Mixitup` (86ko minified)!! That's the same size as `jQuery`! 😮 

Here is an exemple of the relative size of `Mixitup` comparing to all other assets of my website.

![mixitup](https://user-images.githubusercontent.com/10623367/31488472-00855cd8-af3e-11e7-9048-f24fd5ffed0b.png)
_**assets sizes diagram of a classic website**_

To make a comparaison, you might also take a look at `Shuffle`, a very nice library that does the same filtering job with a quarter of the size of `Mixitup` (19.1ko minified):

[https://github.com/Vestride/Shuffle](url)

Is it possible to cleanup the code to make it lighter and more efficient or every pieces of code is needed here?

Cheers

**Comment by jimblue** [comment]
Hi @patrickkunka, did you read this?

**Comment by patrickkunka** [comment]
Hi Jim, it's a good question but currently no, it's not possible to easily "clean up" the code or reduce the size. MixItUp is not like any other similar piece of software because it is truly responsive-friendly and does not rely on reverse engineering layout via absolute positioning (e.g. Isotope, Shuffle). This is unfortunately not a trivial task and requires a significant amount of geometry code, but is more performant as a result, respects CSS and media queries, and does not create resize jank. The MixItUp core also contains the following distinct areas of functionality:

- Geometry
- Animation
- Extensions base architecture
- Utility library
- Controls
- DOM selectors API (filter, toggle, sort, multimix)
- Dataset API (filter, toggle, sort, multimix)

In a future major version (probably v4), Controls, DOM selectors API and Dataset API will most likely be moved out of the core and into optional open source extensions as not everyone needs all three.  This should reduce the weight of the core for those users only wishing to use dataset, but for the majority of users, all of these areas are needed (with the exception of dataset which is a fairly lightweight addition). I'll also move it to transpiled ES6 at that point and drop IE8-9 support, which should save some size too.

MixItUp 3 is certainly pretty hefty, but I feel confident in saying you won't find all of this functionality in any other piece of software. I can't say when I'll have time to start working on v4, but probably mid to late 2018.

**Comment by jimblue** [comment]
Thank you for so much precision. The v4 roadmap is really impressive, I can't wait for it.

Cheers

**Comment by patrickkunka** [comment]
You're welcome, thanks for understanding!
