### ISSUE TITLE
hash filter on load active state

### ISSUE THREAD

**Issue by nandoblanco** [patrickkunka/mixitup#371]
going to a page with hash + filter in url loads up fine and filters fine, but I'm trying to get the active state to show as well...  this is only an issue when the url comes from another page, once on the page clicking filters creates active states no problem... 

I tried the following with hard coded hash (since I wasn't sure if i was passing the hash correctly) but even hard coded hash don't seem to work.

link: https://goo.gl/NGwfBA 

```
//changes the top center text
$('.mixitup-control[data-filter=".doctorofeducation"]').trigger('click'); 
//bolds the filter link
$('.mixitup-control[data-filter=".doctorofeducation"]').addClass('mixitup-control-active');
```
You can see from the source code I tried them inside a window.onload function, the getSelectorFromHash function and the getFilterFromHash function... 

I'm not sure what else to try... 

thanks in advance!

**Comment by patrickkunka** [comment]
Hello, apologies for the late reply. Did you manage to fix this? I checked out the link and it appears to be working fine. What do you mean by the "active state"?

FYI you might want to use history.replaceState() instead of history.pushState() so that a browser history item isn't created each time you filter. There's a comment in the demo code where you can make this change.

I will close for now, but let me know if you want me to reopen.
