### ISSUE TITLE
Pagination hiding elements when on same page

### ISSUE THREAD

**Issue by sophanox** [patrickkunka/mixitup#373]
Hey there,

I'm using the pagination extension with the following config:

```
      pagination: {
        limit: 10,
        maintainActivePage: false,
        loop: true,
        hidePageListIfSinglePage: true,
        generatePageStats: false,
      },
```
At the moment, whilst I have a limit of 10 mixitup elements per page, there are currently only 4 mixitup elements. I've found that if I try to paginate using the last element, the elements above it will go into the hidden state. This is the incorrect behaviour because, as there's no other pages, the mixer shouldn't actually change at all as the current element is on the same page. 

I believe this is a bug (or something in my config), because if I set hidePageListIfSinglePage to false, then use the arrows to change the page, all the elements reappear as they should.

I've tried to demonstrate this through the getState() and the console. If you see in the below image, the only command I've issued is to paginate to that particular elem, which is on page 1 (the current page). This then results in all the elements being hidden.

![image](https://user-images.githubusercontent.com/19409202/31887690-37e6313c-b7f1-11e7-9854-2fb8bbf2723e.png)

Is this a bug? A workaround could be to determine if the selected element is on the current page, and only filtering if it is...but I can't see a way to do that in the available API methods.

Thanks

**Comment by patrickkunka** [comment]
Hi @sophanox,

I believe this is the expected behavior.

What you are doing by passing an element reference to the `.paginate()` method, is paginating via an "anchor" element (this is example 3 in the `.paginate()` docs example). Meaning you are telling MixItUp to create a new page with a limit of 10 elements, starting from your anchor element.

Because your anchor element is the last target, and there are no targets after it, this results in a page with only one element.

FYI - the `loop` config applies only to the pagination controls - meaning that next and previous buttons will take you from the first page to the last and vice-versa.

It sounds like you may be trying to do something else by paginating using an element, so if you could explain why your UI requires this, I might be able to help more.

**Comment by sophanox** [comment]
Ahhh I see! Sorry I was under the impression that it would browse to the page with that particular element on. Having read the example properly now I see I misundersood.

That's what I'm trying to achieve, I give the mixer an element or an ID and it browses to that page. Is that possible, or will it require some sort of DOM interaction outside of mixitup?

Thanks a lot for getting back to me :)

**Comment by patrickkunka** [comment]
Hmm.. MixItUp doesn't have a built in way of knowing what page any particular element sits on, but you could write some custom JavaScript to find out, and then send the page number to MixItUp.

Firstly, we need to obtain all targets matching the current filter, regardless of pagination. This is available via the `state.matching` property:
```js
var myTarget = document.getElementById('taskid-5');
var state = mixer.getState();
var matching = state.matching; 
var currentLimit = state.activePagination.limit; // e.g. 10
```
Now we need to find the index of our desired element, within the list of matching targets.
```js
var targetIndex = matching.indexOf(myTarget) + 1; // e.g. 4 (we add 1 because indices typically start from 0)
```

Finally, we need to find out what the page number of this target would be, given that we have a limit of 10, and it has an index of 3. This will give us a page number starting from 1, which we can send to the paginate method.

```js
var pageNumber = Math.ceil(targetIndex / currentLimit); // 1

mixer.paginate(pageNumber);
```
Let me know if that works.

**Comment by sophanox** [comment]
Works like a charm :)

Thanks so much!
