### ISSUE TITLE
Filtering by hash with select

### ISSUE THREAD

**Issue by in-session** [patrickkunka/mixitup#379]
Hi again,

small problem with hash and selectbox, after filterin of color and size, the hash is as follow:
#color=green&size=square

After removing the color as filter the chash is:
#color=&size=square

correct would be:
#size=square

Cheers Chris

**Comment by patrickkunka** [comment]
Hi - this seems to be related to an issue with the MultiFilter `.getFilterGroupSelectors()` API which wrongly returns an empty string for a `<select>` with no value. I'll get this fixed in a future version.

In the meantime, you can make the following adjustment to the `serializeGroupsState()` function in the hash demo code to avoid this problem:

```js
/**
 * Serializes a groupsState object into a string.
 *
 * @param   {object}    groupsState
 * @return  {string}
 */

function serializeGroupsState(groupsState) {
    var output = '';

    for (var key in groupsState) {
        var values = groupsState[key];

        if (!values.length || (values.length === 1 && values[0] === '')) continue; // check for empty string in array

        output += key + '=';
        output += values.join(',');
        output += '&';
    };

    output = output.replace(/&$/g, '');

    return output;
}
```

**Comment by patrickkunka** [comment]
This has now been fixed in the latest MixItUp MultiFilter version (v3.3.1), which you can download from your account.
