### ISSUE TITLE
onMixClick not working on filter buttons, but onMixStart does

### ISSUE THREAD

**Issue by nolybom** [patrickkunka/mixitup#386]
In order to scroll the viewport to the right spot i do this:

```js
var containerEl = document.querySelector('.container');

var mixer = mixitup(containerEl, {
    classNames: {
        elementFilter: 'filter'
    },
    multifilter: {
        enable: true
    },
    callbacks: {
        onMixClick: function(state, originalEvent) {
            $('html, body').animate({
                scrollTop: $('#page-title').offset().top + 83
            }, 'fast');
        }
    },
    animation: {
        effects: 'fade translateZ(-100px)'
    }
});
```

Unfortunately it doesn't work when clicking on 

```html
<button class="filter" data-filter=".category">Category</button>
```

But as the title says "onMixStart" works.

**Comment by patrickkunka** [comment]
I believe this is because you are are using the MultiFilter extension. MultiFilter controls are not bound to the mixer in the way that the normal MixItUp controls and don't currently invoke this callback, although I agree that they should. I'll get this sorted in a future version.

In the mean time, I would strongly suggest that you trigger your scroll behavior using the `onMixEnd` callback. This means that all mixitup animations and height changes will have completed when your jQuery code is called, and any geometry calculations will be accurate. Doing this at the start of a MixItUp operation can often cause unpredictable scrolling.

**Comment by patrickkunka** [comment]
This has now been fixed in the latest MixItUp MultiFilter version (v3.3.1), which you can download from your account.

**Comment by sebastianbaumann** [comment]
onMixClick callback is not firing if you are using multifilter extension in combination with input type checkbox for filtering, which uses value instead of data-filter.

**Comment by patrickkunka** [comment]
`onMixClick` only works with clickable UI controls (filter and toggle buttons). UI such as radios, checkboxes, and selects do not emit `click` events (they emit `change` events), and are therefore not handled by this callback.

FYI, the `onMixClick` callback was specifically added to intercept and "prevent default" on click events, for people that were forced to use `<a>` tags as their filter controls. This was a feature request by a few people who were limited by their CMS's templating engine IIRC.

As I suggested to the OP, you should be fine using `onMixStart` or `onMixEnd` callbacks to trigger arbitrary custom functionality in response to an operation. If not, please let me know what you need this for and I can hopefully direct you to another solution.

**Comment by sebastianbaumann** [comment]
Hey Patrick. Thanks for your fast response. My fault… totally forgot about the `change` event for checkboxes. Interestingly the `onMixClick` was emitted though, when I exchanged `value` with `data-filter`.

I ended up using the `onMixEnd` callback to trigger my custom scroll event. Works fine, but of course there is some delay.
