### ISSUE TITLE
How to add new control buttons after create mixer?

### ISSUE THREAD

**Issue by moebiussurfing** [patrickkunka/mixitup#397]
Hello, thanks a lot for this! I am just learning how to use it.

I want to create the control buttons on the fly after a backend server query, asking for the items to add to the container. The idea is to show only the buttons (that represent tag names) that the answer of listed items contains. (And not all the tags in all items on the server)

I tried to create the mixer without the control buttons first, and then to add the items to the container and the control filter buttons after. But the buttons aren't working, no filtering at all.

What can I try?

Maybe to add all the items tags on the server at first, and just hide the not required buttons on the query request answer?

(Also I have to disable animations before I add the container items, to avoid the error about queue is full...There is some better solution to this?)

Thanks!

**Comment by patrickkunka** [comment]
If you're going to be adding/removing control buttons after instantiation, you need to set the `controls.live` configuration option to `true`. Otherwise controls will be bound on instantiation only.

```js
var mixer = mixitup(containerEl, {
    controls: {
        live: true
    }
});
```

Regarding, the queue full error when adding items, could you show me what your insertion code looks like?

**Comment by moebiussurfing** [comment]
Thanks Patrick for your reply!
it worked! with: 
```
controls: {
        live: true
} 
```

I am adding the items like this: It's on a loop sometimes with 400 or 10 items... And after around the third item i can see the queue errors on the console. 
```
// NEW DIV:
var newHtmlBox = '<img src="'+ seedURLpng +'"><p class="name">'+ seedName +'</p><p class="owner">'+ seedOwner +'</p><p class="tags">'+ seedTags +'</p><p class="number">'+ seedCounter +'</p>';
var newDiv = '<div class="item '+ seedOwner +' '+ seedName +' '+ seedTags +'" data-ref="mixitup-target">'+ newHtmlBox +'</div>';
mixer.insert(newDiv);
```

I have another doubt if you don't mind. I want to erase and empty all the container and mixer elements to perform new query searches to the server. Do you think thats a good way?:
```
// DESTROY GRID:
mixer.destroy();
$(".container").empty();

// CLEAR FILTER BUTTONS:
$("#filterTags").empty();
$("#filterUsers").empty();

// RECREATE MIXITUP GRID:
mixer = mixitup(containerEl, {...
```
On your demo examples the remove example iterates item by item...

**Comment by patrickkunka** [comment]
You can insert an infinite number of items in one go using the `.insert()` method. So you don't need to insert them one at a time.

You should change your loop to something like the following:

```js
var $itemsToInsert = $();

for (... your loop logic here ...) {
    $itemsToInsert = $itemsToInsert.add('<div...></div>');
}

// We now have a list of all new elements to insert, which
// we can pass to the insert method in one operation:

mixer.insert($itemsToInsert);
```
This example uses a jQuery collection, but you could do the same with vanilla JavaScript by creating in-memory DOM elements for each element, and appending to an array or document fragment before passing to MixItUp (jQuery makes this a bit easier by automatically converting your HTML strings into in-memory DOM).

Regarding removing the mixer, yes that is the correct way if you want a completely new mixer. If you want to keep the same mixer running, but remove all its items before re-adding new ones, you can follow exactly the same pattern as above, but using the `.remove()` method instead of `.insert()`.
