### ISSUE TITLE
[MixItUp MultiFilter] Searching by text input - Implement diacritics map replacement for accented characters

### ISSUE THREAD

**Issue by robertUzias** [patrickkunka/mixitup#402]
Hello, it's me again. Sorry for posting so many issues. I'm implementing the full pagination + multifilter + search bar mixitup demo on my project, but seems like the search filter bugs when I try to search a word with accent mark (acute). Example:

`< fieldset data-filter-group class="text-input-wrapper">
            <input type="text" class="form-control search" data-search-attribute="data-name" placeholder="Search" />
</ fieldset >`

This code search for data-name. Let's say I have a data-name="resuméya". When I type "Resumé", it filters correctly, but exactly when I type the next letter "y", it doesnt filter anything. Could you help me with this one? Thanks again!

**Comment by patrickkunka** [comment]
I've just looked into this, and the problem is related to the fact that the multifilter extension currently lowercases and strips all special characters (non word characters) out of the input, and replaces them with spaces.

So for example, "Resuméya" becomes "resum ya".

This is to make sure that things like punctuation, capitalisation etc are all ignored when searching for a less brittle search. The idea is that your user shouldn't have to enter an exact match of every accent and special character. This does relies on special characters also being stripped out of the values in DOM.

Unfortunately, as a native english speaker, I didn't really consider the problem of accents. Could you tell me if it would be normal for a Spanish speaker to type in every accent perfectly when searching (for example using Google)?

It's worth nothing that this kind of searching (using DOM querying) is never going to be very powerful. The kind of affordances (like partial matching, fuzzy search) that a typical server-side search would provide are never going to be possible through DOM querying which is very crude.

For now, I would suggest stripping and replacing all special characters and accents from the values in your HTML, and hoping that your users don't enter accents when searching.

Depending on what back-end you are using, you should be able to find a regular expression function to do this.

So your HTML would look something like this, for example:

```html
<div class="mix" data-name="resumeya">Resuméya</div>
```
I will leave this issue open and integrate an accurate character replacement map into the extension, rather than just replacing with spaces when I get a chance. That way - "Resuméya" will become "resumeya" instead of "resum ya", which will then always match the HTML if you can do the same on the back-end.

Hope that all makes sense.

**Comment by robertUzias** [comment]
Hello.

When it comes to a google search we (most spanish native speakers) don't really bother writting every accent since the google's search engine itself corrects/suggest the results based on the "keyword". However, when it comes to searching for something more specific (a product named "termómetro", for example) in a website, we (mostly) indeed take more care about accents since it's something very reinforced in our culture. 

You were very clear and I understood perfectly. That's a good solution for now, since it can decrease the percentage of error. I think I could also replace on a keydown event the accented letter by it's non accented version (á => a). Very interesting.

I will be taking notice and be attentive to any other thing I can support with. Thank you.

**Comment by patrickkunka** [comment]
Thanks for the information! I will try to get this done at thev weekend.

**Comment by patrickkunka** [comment]
Hi @Munoz085,

I've gone ahead and done this. All accented characters will now be replaced with non-accented versions before the DOM is queried.

You can download the latest version of the multifilter extension (v3.3.2) from your account.

**Comment by robertUzias** [comment]
That's awesome. What else can I say. Just great.
