### ISSUE TITLE
Reset filters when "all categories" selected with multiple filter categories

### ISSUE THREAD

**Issue by sensaetions** [patrickkunka/mixitup#412]
Hello,

I came across this example of using checkboxes and having the ability to reset filters when the "all categories" checkbox is selected. Thank you for this example. I found this to be very helpful. It works great with one group of checkboxes. How can it be adapted to work with multiple checkbox groups?

**Comment by patrickkunka** [comment]
Hi,

If you want to do anything with multiple groups, the MultiFilter extension is probably the easiest way if you don't want to write any custom JavaScript.

There is a demo included in the extension called "Checkboxes" which shows three checkbox groups with a single reset button which clears all three groups (effectively resetting them to "all".

If you wanted a reset button in each group, you would adjust the markup structure to make each `<fieldset data-filter-group>` into a `<form data-filter-group>`, which would then allow you to add a "reset" button inside each filter group.

If you really want to use a checkbox for "all" instead of a reset button, as in https://demos.kunkalabs.com/mixitup/checkboxes-with-reset-checkbox/, then you would have to write some custom code, as the multifilter extension doesn't include this functionality.

Essentially, where you have one change handler function for one group in the above demo, you would great a new change handler for each individual group of checkboxes. You would store the values of each group in an array of active filters, and then call a shared function every time any group's value changes which concatenates all the values together according to your desired logic.

I hope that helps.

**Comment by sensaetions** [comment]
Hi @patrickkunka, thanks for your response.

So if I want the ability to have a "all" reset button for each `data-filter-group`, I can take your approach of changing the markup structure so each fieldset is a form. 

However, I want to clarify: does this setup (mentioned above) allow for the "AND" multifilter function so that all of the group's value changes from all forms are concatenated into a single logic? Or is this where you're saying that it will require custom handler functions for each form group?

Thanks in advance.

**Comment by patrickkunka** [comment]
If you use the multifilter extension - you can easily customise the logic between and within filter groups without any custom code. This is the main purpose of the extension. By default, you will get "OR" logic within a group, and "AND" logic between each group. All concatenation of selectors is handled by the extension.

The only limitation of the extension is that it doesn't include functionality to use a checkbox element as a reset button, as it expects an actual `<button type="reset">`, which triggers a native "reset" event on a form. Which is why you'd also need to make each filter group into a form. This is described in this documentation: https://www.kunkalabs.com/mixitup-multifilter/docs/get-started/ under the heading "reset buttons".

Therefore, if you really have to use a checkbox for "all" rather than a button, you wouldn't be able to use the multifilter extension, and would have to write the entire thing from scratch including event handling and selector concatenation.
