### ISSUE TITLE
MixitUp migration from 2 -> 3

### ISSUE THREAD

**Issue by Toubef** [patrickkunka/mixitup#414]
Hi,

I just migrated from version 2 and I have it up and running but for some reason the animation is no longer smooth. It doesn't have that flow / animation anymore like it had with version 2.. Could I have some settings that is causing this or?

Br,
Toube

**Comment by patrickkunka** [comment]
Please post a link to your project and I can take a look. Thanks.

MixItUp 3 doesn't have a "loading animation" like MixItUp 2, but otherwise all animations are the same. If you want to add a MixItUp 2 style loading animation, there is a demo example here: 

https://demos.kunkalabs.com/mixitup/loading-animation/
