### ISSUE TITLE
Reset hierarchical filter

### ISSUE THREAD

**Issue by paul-keller** [patrickkunka/mixitup#416]
I'm using the MultiFilter and have set up a hierarchical filter with 3 different select fields. After selecting the first category, the subcategories in the next select box are show. The same for subsubcategorie. This works fine.
As soon as I change the first category, the filters for subcategory and subsubcategory are not reset.
Of course I have a reset button to reset all. That works. But I would like to reset the filters as well, as soon as I change the first category. The display of the subcategories are adjusted correctly, but MultiFilter keeps the subcategories and does not display the objects correctly.

**Comment by patrickkunka** [comment]
The extension is listening to 'change' events from your form UI. As soon as you change the value of your first filter group, a new selector string will be built based on whatever the values of each filter group are at that time, and then sent to MixItUp to filter the targets against. Even if you reset your other `<select>` elements at this point, it will be too late.

We therefore need to manipulate the values of second and third groups, before the selector string is generated. For this, you can implement a custom callback handler for the `onParseFilterGroups` configuration option.

Your function will receive an argument called a "command object", which contains all information about the current mixitup operation. This allows us to change the values produced by the UI before they are handled. We can either create a new command object or mutate the original one, but we must return a valid command object to the callback function for MixItUp to handle.

```js
function handleParseFilterGroups(command) {
    // ...manipulate and return the command object...
    return command;
}

var mixer = mixitup(containerEl, {
    multifilter: {
        enable: true,
    },
    callbacks: {
        onParseFilterGroups: handleParseFilterGroups
    }
});
```

So in your case, you need to know if the operation was caused due to a change of the first filter group. Let's say we have the following markup for our first filter group with a select element inside:

```html
<fieldset data-filter-group="color">
    <select>
        <option value=".green">Green</option>
        <option value=".blue">Blue</option>
        <option value=".pink">Pink</option>
    </select>
</fieldset>
```

```js
var colorGroup = document.querySelector('[data-filter-group="color"]');
var hasColorGroupChanged = false;

function handleColorGroupChange() {
    hasColorGroupChanged = true;
}

colorGroup.addEventListener('change', handleColorGroupChange);
```

Notice that I have also added a flag `hasColorGroupChanged` that we can check in our `handleParseFilterGroups()` function, to see if the operation was caused by a change to the color group.

We can now fully implement `handleParseFilterGroups()` callback function:

```js
function handleParseFilterGroups(command) {
    if (hasColorGroupChanged) {
        // Read the value(s) from only the color filter group
        var colorGroupValues = mixer.getFilterGroupSelectors('color'); // ['.green']

        // Override the `filter.selector` property of the command object with only
        // these values

        command.filter.selector = colorGroupValues.join(','); // '.green'

        // Reset the flag for subsequent use

        hasColorGroupChanged = false;
    }

    // Return the command object to mixitup

    return command;
}
```

That should be everything you need to work with the first group. If you want to do the same for the second group as well, you can set up another handler for the second group, and extend `handleParseFilterGroups()` handler with your desired logic, taking into account the hierarchy of values as desired.

I hope that helps!

**Comment by paul-keller** [comment]
Thanks! Your answer really helped! I got it running as I need it!
