### ISSUE TITLE
Problems with Columns-based-layout in Chrome

### ISSUE THREAD

**Issue by srueegger** [patrickkunka/mixitup#418]
Hi

I love mixitup - but i have a Problem with Google Chrome. On my Site: https://sa.compresso.ch/partner-und-sponsoren/

works mixitup very fine with Firefox.

When you Clicking some of the Controls in Google Chrome (Mac and Windows) kills the complete Browser.

**Comment by patrickkunka** [comment]
Hi,

It looks like the problem is related to your use of a columns-based layout.  Unfortunately this type of layout can be very unpredictable with MixItUp as the browser's column packing algorithm differs from vendor to vendor (Chrome's has changed within the last 12 months).

I would recommend switching to a standard flexbox or inline-block based layout (which I appreciate may not work with your design), or if not an option, disabling animations. I have tested both options with your project and both work fine.

I hope that helps,
Patrick

**Comment by jmvn** [comment]
Sorry for commenting in a closed thread but just as an FYI: If you're using column based layouts (which work fine for me in all browsers) there seems to be an issue with Chrome 66 and up where this standard styling line can cause filter elements to become unclickable: 
backface-visibility: hidden; /* prevents flicker in chrome */

Removing it fixes the issue, and at least I'm not having any issues with flickering.
