### ISSUE TITLE
[MixItUp Multifilter] Programmatically setting group filters or toggles on load

### ISSUE THREAD

**Issue by johannesdb** [patrickkunka/mixitup#421]
Hi,

I have a setup where I have several toggle buttons. I need one of them to be toggled on load.

If I set the load {filter: *class*} to set the toggle button toggled, it acts as if it is a filter - I cant untoggle it and it resets if I press any of the other toggle buttons.

It would be great if I could specify a state for a specific toggle button on load like this:

load: { toggle: *class*}
just like I do with a filter.

**Comment by patrickkunka** [comment]
Unlike standard MixItUp controls which are 2-way bound, MultiFilter filter group controls are 1-way bound.

This means that they will not react to changes via the `.filter()` API (or `load.filter` option). This is because for any given compound selector, MultiFilter has no way of knowing how to it break it up and distribute across filter groups accurately.

Instead, MultiFilter controls have their own APIs if you wish to write or read them programmatically. In your case you will need the `setFilterGroupSelectors()` API method.

Before you can use this you will need to "name" your filter groups, by adding a value to the your `data-filter-group` attributes: 

```html
<fieldset data-filter-group="color">
    ...
</fieldset>

<fieldset data-filter-group="shape">
    ...
</fieldset>

<fieldset data-filter-group="size">
    ...
</fieldset>
```

We can now interact with the groups via the API:

```js
var mixer = mixitup(containerEl, {
    multifilter: {
        enable: true
    },
    animation: {
        enable: false // disable animations
    }
});

// pre-activate the `.circle` and `.triangle` toggles for the `shape` group
mixer.setFilterGroupSelectors('shape', ['.circle', '.triangle']);

// parse all groups and trigger an initial filter operation
mixer.parseFilterGroups();

// re-enable animations for all subsequent operations
mixer.configure({animation: {enable: true}});
```

In this case, since we are setting the active filters on load, we may wish to disable (and then re-enable) animations, to prevent an initial transition from "all".

More information is available in the API docs: https://www.kunkalabs.com/mixitup-multifilter/docs/api-methods/

Hope that helps.

**Comment by johannesdb** [comment]
Perfect! Thanks!

**Comment by johannesdb** [comment]
I am deeply impressed with your software and answer! It took me less than 2 minutes to fix it :-)

Thanks you!

**Comment by patrickkunka** [comment]
Great - thanks for the feedback!
