### ISSUE TITLE
[MixItUp MultiFilter] Triggering a filter operation after programmatically checking/unchecking checkboxes

### ISSUE THREAD

**Issue by thoweber** [patrickkunka/mixitup#422]
Version used: 3.3.2

Changing the checkboxes "checked" property prior to calling parseFilterGroups() has no effect on the selector used to filter the contents. If I trigger a 'click' event on the checkbox, the change is detected and applied.

**Comment by patrickkunka** [comment]
Hi,

I'm assuming you mean when programmatically checking/unchecking a checkbox via JavaScript?

This is because when you manipulate the state of a checkbox, no "change" event is emitted, which is what the multifilter extension is listening for.

Simply ensure you emit a change event once you have made your changes, and you should be good to go:

```js
// obtain a reference to one or more checkboxes you wish to manipulate:
var green = document.querySelector('[value=".green"]');

// check or uncheck the checkboxes via JavaScript
green.checked = true;

// create a custom event
var ev = new CustomEvent('change', {bubbles: true});

// dispatch the event from the input (or parent fieldset is manipulating multiple inputs)
green.dispatchEvent(ev);
```

The mixer will detect the change and re-filter automatically. In this case, you do not need to call `parseFilterGroups()`.

The alternative approach is to manipulate the value of a group via the `setFilterGroupValues()` API method, in which case you would need to call `parseFilterGroups()` afterwards. This method is more suited to standard filter or toggle button based UI, where no DOM manipulation is required.

```js
mixer.setFilterGroupValues('color', ['.green']);
mixer.parseFilterGroups();
```

**Comment by thoweber** [comment]
Hi Patrick,

Thanks for your answer. I had already solved my issue using the setFilterGroupValues/parseFilterGroups approach.

However, I think you should amend the example for parseFilterGroups() on https://www.kunkalabs.com/mixitup-multifilter/docs/api-methods/:

```js
var checkboxes = Array.from(document.querySelectorAll('.my-group > input[type="checkbox"]'));

checkboxes.forEach(function(checkbox) {
    checkbox.checked = true;
});

mixer.parseFilterGroups();
```
This implies that there is no need for events which might be confusing for other users as well.

Best,

Thomas

**Comment by patrickkunka** [comment]
Ah yes of course - thanks for pointing that out. Will get that fixed.

**Comment by patrickkunka** [comment]
Fixed now, cheers.
