### ISSUE TITLE
Sort newly added elements before they appear in Mixitup

### ISSUE THREAD

**Issue by sophanox** [patrickkunka/mixitup#425]
Hey Patrick,

I have a function which dynamically adds items to my container. However, I'm having problems because I can't seem to insert them already sorted. As a result, they can appear out of place dependent on the current sort attribute / direction.

I thought multimix would handle this as it lets you add and sort? However, using this code, for example, has no difference in sorting the items:

` mixer.multimix({ insert: newTaskHtml, sort: mixer.getState().activeSort.sortString, filter: mixer.getState().activeFilter.selector });` 

Is the only option to do something like: check what page the user is on, insert it into a different page, then force a sort?

Thanks!

**Comment by patrickkunka** [comment]
Hi @sophanox,

Because sorting is the most expensive MixItUp operation, there is an internal optimisation to prevent a re-sort if the provided sort string is the same as the current one.

In your case, this will be true. To disable this optimisation, we can turn on the "live sort" behavior via the `behavior.liveSort` configuration option:

```js
mixitup({
    behavior: {
        liveSort: true
    }
});
```

This should allow you to insert AND resort by the current sort string simultaneously. Please let me know if that works for you.

More info here: https://github.com/patrickkunka/mixitup/issues/311

**Comment by sophanox** [comment]
Worked perfectly. Thanks again for the speedy reply!
