### ISSUE TITLE
Foundation / MixItUp "data-toggle" Attribute Interference

### ISSUE THREAD

**Issue by Lazerproof** [patrickkunka/mixitup#426]
It would be great if data-filter, data-sort or data-toggle attributes could be configurable via configuration object. 

When using Mixitup together with Foundation all logic have to be performed via the mixer’s API methods.
`selectors.control` selector doesn't work in this situation as Foundation's events which relies on jquery also bound to these elements which result in error `Uncaught Error: Syntax error, unrecognized expression: #.green`

**Comment by patrickkunka** [comment]
Hi,

Could you provide an example of what you would like to be able to do, and why it is not currently possible?

A reproduction of the error in a jsfiddle would be great too.

Thanks

**Comment by Lazerproof** [comment]
Hi @patrickkunka 
Take a look at this example 
https://jsfiddle.net/4k1eLLyL/5/

I would like to have something like
```
var mixer = mixitup(containerEl, {
    selectors: {
        toogle: 'data-mix-toggle', // default data-toggle
        filter: 'data-mix-filter', // default data-filter
        sort: 'data-mix-sort' // default data-sort
    }
});
```

**Comment by patrickkunka** [comment]
Hi @Lazerproof,

Apologies for the delay, I've just a chance to look at this. Thanks so much for putting it together.

I'd rather not make these attributes configurable because it would require significant changes across codebases. Thankfully there is a solution though.

To summarize, there are two problems caused by the selector collision:
1. Clicks on Foundation UI elements are being handled by MixItUp. This unintentionally causes the mixer to filter by a failing selector, and empties it.
2. Clicks on MixItUp UI elements are being handled by Foundation. This causes an exception in foundation as the values in the attributes are not the expected format.

To solve problem 1, we can use the `data-mixitup-control` trick as you mentioned, which is often recommended to bootstrap users to solve the same problem. This attribute should be added to all controls. More info here: https://github.com/patrickkunka/mixitup/issues/268.

To solve problem 2, we can prevent click events on MixItUp controls from propagating up and being handled by foundation's event listener.

The necessary MixItUp configuration code looks like this:

```js
var mixer = mixitup(containerEl, {
    selectors: {
        control: '[data-mixitup-control]'
    },
    callbacks: {
        onMixClick: function(state, e) {
            e.stopPropagation();
        }
    }
});
```

Tested in your fiddle, and working correctly. No unintended filtering, and no errors.
