### ISSUE TITLE
Smooth animations with nth-child-based styling

### ISSUE THREAD

**Issue by jeffceriello** [patrickkunka/mixitup#432]
Hi,

I have a grid populated via API with dataset. The grid items have different width depending on the row using flexbox and when the items are filtered their width resizes sharply when ideally it should grow gradually instead of jumping or perhaps fade out and then in in the correct size. I've applied css transition with no success. I've then tried to disable mixitup animation all together and thought of using css only by adding and removing classes onMixClick and onMixEnd but that also didn't work as expected as in it didn't animate like it should.

Is there a way of achieving what I need or should I just look for another approach?

Here is a fiddle with the issue I'm experiencing https://jsfiddle.net/2h66840k/24

Thanks for the help and for this great plugin!

**Comment by jeffceriello** [comment]
Hi Patrick, any help with this would be hugely appreciated. Are you able to point me to the right direction?

Here is an updated link https://jsfiddle.net/2h66840k/26/

Thank you

**Comment by patrickkunka** [comment]
Hi Jeff,

Apologies for the delay in response. Also thanks for taking the time to put together an isolated test case.

Unfortunately mixitup's state-to-state animations are not compatible with nth-child based styling, which  is how you're targeting the elements in your container to affect their widths. This is because all elements coming in, going out, or staying, need to exist in the DOM simultaneously at the point of an animation, so an element's index before or after an animation, will not be the same as it is during an animation, and should therefore be considered meaningless when using MixItUp.

If you can find a way of styling your grid which relies only the natural sizing (based on an element's contents), or possibly by persistent class names (as long as you don't change them during an operation), then you should be OK, but most likely you won't be able to use this particular layout and get the standard MixItUp animations.

However, if you're happy to fade everything out and then everything back in again between states (without state-to-state transitions), then you should be able to work around this. You shouldn't need to use your own animations - this will only interfere with what MixItUp is doing.

I've updated your fiddle to demonstrate:

https://jsfiddle.net/2h66840k/37/

I've speeded up the animations a bit to account for API latency and the fact we need to fade out the whole set between states.

Hope that helps!

**Comment by jeffceriello** [comment]
That works beautifully! Thank you so much, Patrick :)
