### ISSUE TITLE
Infinite Scroll + Multifilter + CHash

### ISSUE THREAD

**Issue by in-session** [patrickkunka/mixitup#433]
Hi Again,

really very good work you have done there, much more easier to handle as isotope.

I am currently facing the problem that I would like to insert infinite scroll: https://infinite-scroll.com/
base on the default multifilter example of "programmatic-filtering-by-url".

When the next page is loaded, the filter is not applied to the new items
Can you help me implement that for mixItUp?

Here is a small example with the infinite scroll together with isotope 

```
// with Isotope & jQuery
// init Isotope
var $grid = $('.grid').isotope({
  // Isotope options...
  itemSelector: '.grid__item', 
});

// get Isotope instance
var iso = $grid.data('isotope');

// init Infinite Scroll
$grid.infiniteScroll({
  // Infinite Scroll options...
  append: '.grid__item',
  outlayer: iso,
});
```

Greetings Christoph

**Comment by patrickkunka** [comment]
Hello,

Unfortunately, MixItUp and infinite scroll are not compatible.

You can either use Isotope (since are written by the same author, they integrate well)

or..

You will also find that our Pagination Extension can be used to achieve something similar to infinite scroll, by programmatically increasing the "items per page" limit as the user scrolls down. There is a demo entitled "Infinite Scroll" within the MixItUp Pagination package, which owners of the extension will have access to.

**Comment by in-session** [comment]
Hi Patrick,

ok many thanks for the information, I will have to think again.
Since in total 1,000 data records have to be loaded and I think loading all at once will be a performance issue.

Greetings Chris
