### ISSUE TITLE
Some items animate into place, some snap

### ISSUE THREAD

**Issue by jhkerschner** [patrickkunka/mixitup#437]
I'm using MixItUp on this page http://mower.staging.wpengine.com/our-people/. I noticed that when I trigger a filter, then trigger another one, the animation happens for some of the items, but then the rest just display and snap into place. i have tried different configuration, but it still continues to snap into place. If you have some time to check it out quick and maybe point me in a direction, that would be awesome!

**Comment by patrickkunka** [comment]
Hi there.

Thanks for the link.

I've taken a look and the issue is that you have a CSS rule `mix-blend-mode: multiply;` applied to an element within your targets for your photo treatment effect. Unfortunately, this is thrashing the GPU to such an extent (probably in combination with the images) that it can no longer fade in the opacity of the targets, which results in a sudden snap to view.

Simply disabling that rule fixes the issue, but I assume that's not an easy option as the treatment looks like an important part of the design. You may have to decide between using mixitup animations or the color fade.

If it's of any help, I can already think of two possible work arounds.

1 - Apply the `mix-blend-mode` effect on `mouseenter`, and remove it a few hundred milliseconds after `mouseleave`, giving the animation time complete. This would require writing some custom JavaScript, but would mean that that rule is never present when a MixItUp operation is in progress.
2 - A more old-school solution would be to have a separate image with the treatment pre-rendered, absolutely positioned above the first, with zero opacity, then fade between the two on hover. Obviously, this would have a content creation overhead, but you could probably automate in PhotoShop.

Hope that helps.

**Comment by jhkerschner** [comment]
Thanks for the input. I temporarily removed the overlay that had the multiply effect. When I filter, it still still seems like it's snapping the bottom rows. The first row seems to slide in nicely thought. Maybe this is how it works when there are a bunch of items?

**Comment by patrickkunka** [comment]
Thanks for the feedback - I had another look and I can see you are missing `align-content: flex-start;` on your container.

With that added and the multiply effect removed, seems to be working perfectly.

**Comment by jhkerschner** [comment]
Awesome, just tried that and it's working perfectly! Thanks for your help!
