### ISSUE TITLE
Inserting targets into multiple instances with nested DOM structure

### ISSUE THREAD

**Issue by johannesdb** [patrickkunka/mixitup#444]
Hi

I have pages with up to four different paginations. I know that I can bind the different paginations to different lists of elements.

The problem is that I use the append function to insert elements into the DOM. But I can only append elements as children to the container. As all the controls for filtering, searching and pagination I need to append the elements to a child of the container - not the container itself.

Eg:

`<div id="container">
      <div id="controlpanel"></div>
      <div id="elements">
          appended elements
      </div>
    <div id="paginationcontrols"></div>`

Is it possible to either change the mixitup instance container when appending the elements and the revert it after? Or to specifiy children when appending the elements?

I am using append as I need to render almost 1000 elements and it is way faster to insert the elements after load with js than letting the browser go through a larger html file.

You can see an example here: https://guide.ølfestival.dk/oel/
If you select a beer (øl) you can see that there is a list of other beers, news and activities. Right now I have disable pagination on these pages as I can't set the scope to local and still append the elements.

**Comment by patrickkunka** [comment]
Hi Johannes, 

By default, MixItUp will create a "virtual" container, by searching for the immediate parent of all targets found in the DOM instantiation, in most cases this is the actual container, but if you are separating your targets from your controls with additional nesting, it would be a child of the container e.g:

https://demos.kunkalabs.com/mixitup/multiple-instances-local-control-scoping/

When you insert targets into the DOM, they will always be inserted into the "virtual" container.

In order for it to correctly the detect the virtual container, however, you do need to start with some targets in the DOM. It sounds like because you are starting with an empty container and then loading all your targets by JS, MixItUp does not know where you want to insert your targets, and just inserts them as children of your top level container.

The best solution would be to create a single "placeholder" target in each of your MixItUp containers (in your "elements" div), which could be hidden by default (by setting a more specific "load.filter" option). Then when you append your actual content, MixItUp will know where you want them.

I hope that makes sense. Let me know if it works.

**Comment by patrickkunka** [comment]
Assuming this has worked for you and will now close. Please let me know if not and can reopen.

**Comment by johannesdb** [comment]
Hi! I missed your first respons, but will look at it and get back if I need help :-) I think i get the drift :-)

Thanks!
