### ISSUE TITLE
Data-toggle AND data-filter, depending on click or double click

### ISSUE THREAD

**Issue by br0wnie** [patrickkunka/mixitup#450]
I am trying to make it so that when a user single clicks a filter, it becomes the only filter. If they double click a filter, the filter is added as an OR to the current filter(s).

Is that possible?

I am really new to JavaScript and libraries so please forgive my code, but this is what I tried:

```javascript
var containerGrid = document.querySelector('.grid'),
    clickMix = mixitup(containerGrid),
    buttons = Array.from(document.querySelectorAll('.btn'));

const doubleClick = (e) => {
    e.preventDefault();
    if (e.currentTarget.hasAttribute('data-filter')) {
        var filter = e.currentTarget.getAttribute('data-filter');
        console.log(filter);
        e.currentTarget.removeAttribute('data-filter');
        e.currentTarget.setAttribute('data-toggle', filter);
  }
}
```

That successfully replaces the data-filter attribute with the data-toggle attribute when I double click a button. However, the button still seems to act as though it has the data-filter attribute still. I tried adding 
clickMix.toggleOn(filter) but that didn't make a difference (I'm probably using it wrong).

Can you point me in the right direction? I've been trying things from the API method documentation but can't seem to figure it out.

**--Edit--**
I temporarily replaced the code triggered by double click with mixer.hide(). It first filters according to whatever button I clicked, THEN it filters everything out. So I guess that is a clue that the default behavior was occurring before my code ran. I'll have to try messing around with the mixClick event.

**Comment by patrickkunkadazn** [comment]
Hi there,

That's an interesting problem. I can't say I've come across it before, but it may be possible. Have you tried setting the `controls.live` configuration to `true`?

By default, MixItUp will crawl the DOM for your controls once and attach specific click functionality to them by type, on init. By setting `live: true`, we are telling MixItUp that the controls can change (e.g. added/removed/edited) during the a session, and that the functionality of a control must be determined when it clicked only, and not before. This incurs a very minor performance overhead which is why it is disabled by default.

An example integration looks like this:

```js
var mixer = mixitup(containerEl, {
    controls: {
        live: true
    }
});
```

**Comment by patrickkunka** [comment]
Hi there,

That's an interesting problem. I can't say I've come across it before, but it may be possible. Have you tried setting the controls.live configuration to true?

By default, MixItUp will crawl the DOM for your controls once and attach specific click functionality to them by type, on init. By setting live: true, we are telling MixItUp that the controls can change (e.g. added/removed/edited) during the a session, and that the functionality of a control must be determined when it clicked only, and not before. This incurs a very minor performance overhead which is why it is disabled by default.

An example integration looks like this:

```js
var mixer = mixitup(containerEl, {
    controls: {
        live: true
    }
});
```
