### ISSUE TITLE
Apply multifilter to multiple containerEl's 

### ISSUE THREAD

**Issue by jklue** [patrickkunka/mixitup#454]
Is there a way to pass multiple container elements to the same multifilter mixer? I need to sort two kinds of data, but the exact same way. Something like the following?

````
var mixer = mixitup([containerEl1, containerEl2], {
    multifilter: {
        enable: true // enable the multifilter extension for the mixer
    }
});
````
I'm trying to get all the "Profiled Projects", or colored ones, to show up first in the list of projects here: [humanitiesforall.org](https://humanitiesforall.org/). But I need to randomize the projects on page load, hence the need for two container elements.

Thank you!

**Comment by patrickkunka** [comment]
Hi Luke,

You can create multiple mixers in a document by instantiating them one at a time. 

If you wanted to control all instances with a single set of controls, you can use the default "global" control scoping: 

https://demos.kunkalabs.com/mixitup/multiple-instances-global-control-scoping/

If you want each instance to be controlled individually, you would need to set the control scoping to "local", as seen in this demo.

https://demos.kunkalabs.com/mixitup/multiple-instances-local-control-scoping/

In order to share configuration between instances, you can first create a single configuration object, with your multifilter setup, and then pass it to the mixitup factory function each time you call it.

I hope that helps.
