### ISSUE TITLE
Incorporating URL Parameters

### ISSUE THREAD

**Issue by pierrerocket** [patrickkunka/mixitup#460]
Hello,

I am trying to setup a multiple filter almost exactly like this codepen:

https://codepen.io/patrickkunka/pen/iwcap

However we need to be able to also filter by parameters in the URL, for example

http://myurl.local/embedded-modems/?carrier=verizon+att&region=usa+north-america&technology=lte-m

Any suggestions / ideas on how I can accomplish this?

**Comment by patrickkunka** [comment]
Hi there,

For v3, the multifilter extension is designed for this purpose.

There is a demo included in the extension bundle detailing how to implement multiple url hash segments per filter group.

**Comment by pierrerocket** [comment]
Ok great, thanks.  If I had a recommendation it would be to move from hashes to query parameters, and to have the option of updating the URL live on filter.  My coworker ended up cobbling something together to that end.

Thanks, love the script.

**Comment by patrickkunka** [comment]
Great. You can use whatever you want as it's all custom code and not baked into MixItUp. Obviously query params have meaning on the server side and hashes don't which is why they are used in the demo. Regarding updating the URL on filter, all the demos already do this I think?

https://demos.kunkalabs.com/mixitup/filtering-by-url/

**Comment by Criggz97** [comment]
@pierrerocket 
How did you solve to make the MixItUp use query parameters instead? :)

Or does @patrickkunka have som advice on this? :)
