### ISSUE TITLE
Mixitup queue won't process or clear up and animations wont end

### ISSUE THREAD

**Issue by baheego** [patrickkunka/mixitup#463]
Hey, first off thank you for the great project, it'll be pivotal in one of my applications.

I have stumbled into an issue with animated datasets, here's a live example [right here](http://rockstest.com/item_test)
As you can see, it animates just fine the first time when the document loads, however when a filter change happens, or if I attempt to add another mix to the queue every 5 seconds as it refreshes for a JSON API endpoint, it shows me the following error: 

`WARNING: An operation was requested but the MixItUp instance was busy. The operation was rejected because the queue is full or queuing is disabled.`

The way I use mixitup is: I pass an array into the dataset method after I initialize mixitup and ajax a JSON endpoint, which then utilizes the render function that I pass when I initialize the mixitup object, I have tried increasing the queue limit but there seems to be no use as the first dataset process never really ends even though the animation clearly happens the first time on the live page

Adding on: I've tested it out with a dataset containing only 2 array elements and it still wouldn't work, so I know it isnt because of an overload or DOM manipulation or something similar.

**Comment by baheego** [comment]
I also tried debugging ontransitionend events but nothing worked out really.

**Comment by patrickkunka** [comment]
Hi @baheego,

Thanks for the detailed description. I've had a look at your project and the issue is that you have not set a valid selector for the `selectors.target` configuration option. This should be in the form of a DOM selector string.

In your configuration, please change:
```js
{
    selectors: {
        target: 'item_cell'
    }
}
```
to:
```js
{
    selectors: {
        target: '.item_cell'
    }
}
```

FYI - MixItUp will validate all `transitionend` events propagated from targets against this selector to ensure that all expected target transitions have ended, and the animation can be considered done. In your case, all validation would have failed, leaving the transition in a permanently pending state.

Good luck with the project.
