### ISSUE TITLE
Filter not working

### ISSUE THREAD

**Issue by neburdesign** [patrickkunka/mixitup#472]
Hi Patrick,

If I repeat "Bootstrap container" class twice e.g, the filter stop working. 
How can I solve this problem?

Kind Regards
Rúben

**Comment by patrickkunka** [comment]
Hi Ruben,

I'm not exactly sure what you mean, but it sounds like you are targeting your mixitup container with the class `bootstrap-container`, which you are then using elsewhere on your page for non-mixitup related stuff.

The solution is to be much more specific about your MixItUp container. For example, use an ID:

```html
<div class="bootstrap-container" id="mixitup-container">
    ....
</div>
```

Then use that ID to reference the container when instantiating mixitup, instead of the class name.

```js
var mixer = mixitup('#mixitup-container');
```

This way, class names are only used for styling purposes (not javascript).

I may have misunderstood your question however. Perhaps you are trying to create multiple mixitup containers in the same page. If so, please check out these two demos:

https://demos.kunkalabs.com/mixitup/multiple-instances-local-control-scoping/
https://demos.kunkalabs.com/mixitup/multiple-instances-global-control-scoping/

I hope that helps.

**Comment by neburdesign** [comment]
Yes, this solved part of the issue.

FYI:
I'm using the "bootstrap container class" and the Mixitup 3.3.0 container. The Slider Range does not work but, the checkboxes and radio buttons they work.

The other issue I wish to highlight make is this:
I would like to remove all events (Range Slider, Checkbox and Radios for example) from within the HTML file to another file. How can I do this?

Event Radio example:

<script>
    var containerEl = document.querySelector('.container');
    var radiosFilter = document.querySelector('.radios-filter');
    var radiosSort = document.querySelector('.radios-sort');
    var mixer = mixitup(containerEl);
    radiosFilter.addEventListener('change', function() {
        var checked = radiosFilter.querySelector(':checked');
        var selector = checked ? checked.value : 'all';
        mixer.filter(selector);
    });
    radiosSort.addEventListener('change', function() {
        var checked = radiosSort.querySelector(':checked');
        var order = checked.value;
        mixer.sort(order);
    });
</script>

Thank you
Rúben

**Comment by neburdesign** [comment]
Hi Patrick,

Other issue:
How to have multiple groups of checkboxes without giving conflict?

Example:
<img width="1173" alt="filter" src="https://user-images.githubusercontent.com/7307684/47378753-f70b2d00-d6f0-11e8-99a3-b7b3bff95f3d.png">

Please help. Thank you
Rúben

**Comment by patrickkunka** [comment]
Hi ruben,

Firstly, you can easily extract everything in the script tag in your html to a javascript file which you would then load after you load MixItUp.

Secondly, looking at your design, you'll want to use the multifilter extension for this type of UI. This way you won't need to write any custom JavaScript for radios, selects or checkboxes.

You will still have to integrate the range slider yourself however. Please see the following demo for an example:

https://github.com/patrickkunka/mixitup/blob/v3/demos/filtering-by-range/index.html

**Comment by neburdesign** [comment]
Hi Patrick,

Thank you so much for your support.
Now, Range Slider is working and javascript file was been created.

With the new MixItUp 3.0 update, it possible to integrate the message fail (No results found)?
Thanks

**Comment by patrickkunka** [comment]
Great!

Yes, this is very simple. When you select a filter with no results, you will notice that a "failed" class is added to the Container element.

You can create your message as a hidden element within the container which you show with css based on the presence of the failed class.

See the demo here: https://www.kunkalabs.com/mixitup-multifilter/ and select circle and large. You will see the message is faded in.

**Comment by neburdesign** [comment]
Hi Patrick,
Thank you for your feedback.

I use free Mixitup 3.3.0v. Is possible to use "message fail" anyway? Any examples?
Is possible to use range slider with tracking tooltip (tooltip-parent)?

Thank you
Rúben

**Comment by ghost** [comment]
Yes its possible to use the exact same approach with MixItUp "core". The same `mixitup-container-failed` class is part of MixItUp core and will be added to the container whenever you filter by a selector which yields no results.

I just pointed you to that multifilter demo because I didn't add any "failed" error UI to the basic sandbox at https://www.kunkalabs.com/mixitup/

Regarding the range slider question, I don't think this is related to MixItUp. You can use any range slider plugin you want, you just need to handle its "change" event and extract the latest min/max values. Therefore, whether or not you use a range slider with tooltips, is of no concern to MixItUp.
