### ISSUE TITLE
Page Load takes forever with mixitup activated?

### ISSUE THREAD

**Issue by ckmuc** [patrickkunka/mixitup#489]
Hi,
I have a "big" dataset (about 2000 records) and when using activating the MixItUp Script, the site takes forever to be displayed (more than 1-2 minutes) and Chrome also issues a "timeout" warning. 
When removing the Mixer JS  site loads in 2 seconds.

Dev Consolse shows:
![image](https://user-images.githubusercontent.com/1737468/52164461-f02d8680-26f1-11e9-83b2-565de9307d25.png)

Any Idea, what we are doing wrong or how this behavior/long load times could be avoided?

```

var containerEl = document.querySelector('.container');
		var checkboxGroup = document.querySelector('.checkbox-group');
		var checkboxes = checkboxGroup.querySelectorAll('input[type="checkbox"]');
		//var allCheckbox = checkboxGroup.querySelector('input[value="all"]');
		var allCheckbox = checkboxGroup.querySelector('input[value=".none"]');

		var mixer = mixitup(containerEl);

		checkboxGroup.addEventListener('change', function(e) {
				var selectors = [];
				var checkbox;
				var i;

				if (e.target === allCheckbox && e.target.checked) {
						// If the "all" checkbox was checked, uncheck all other checkboxes

						for (i = 0; i < checkboxes.length; i++) {
								checkbox = checkboxes[i];

								if (checkbox !== allCheckbox) checkbox.checked = false;
						}
				} else {
						// Another checkbox was changed, uncheck "all".

						allCheckbox.checked = false;
				}

				// Iterate through all checkboxes, pushing the
				// values of those that are checked into an array

				for (i = 0; i < checkboxes.length; i++) {
						checkbox = checkboxes[i];

						if (checkbox.checked) selectors.push(checkbox.value);
				}

				// If there are values in the array, join it into a string
				// using your desired logic, and send to the mixer's .filter()
				// method, otherwise filter by 'all'

				var selectorString = selectors.length > 0 ?
						selectors.join(',') : // or '.' for AND logic
						'all';

				mixer.filter(selectorString);
		});


		mixer.toggleOn('.cat-2')
		.then(function() {
			// Deactivate all active toggles

			return mixer.toggleOff('.none')
		})
		.then(function(state) {
				 console.log(state.activeFilter.selector); // 'none'
				 console.log(state.totalShow); // 0
		});		
		
```

Chris

**Comment by patrickkunka** [comment]
Hi there,

MixItUp (or client-side, DOM-based filtering in general) is not a viable solution for working with thousands of elements. It is best suited to a small static set of a few hundred items at most.

At that scale, you would be better implementing a server-side solution, with pagination and / or lazy loading, so that the DOM never becomes too heavy.

This is mentioned at the start of the MixItUp "Get Started" page:

https://www.kunkalabs.com/mixitup/docs/get-started/

As mentioned there, if you'd still like to take advantage of MixItUp's animations, the dataset API might be a possible solution for you, but this does mean implementing all your filtering/sorting on the server side over an API, and building your own UI.

Hope that helps
