### ISSUE TITLE
Text field with comparision

### ISSUE THREAD

**Issue by ghost** [patrickkunka/mixitup#490]
Hello Patrick,

can you create text field for filtering by a value and then showing of all results, which are lower / higher then the given value?

Greetings.

**Comment by patrickkunka** [comment]
Hello,

Yes, it is possible to filter results by a numeric range, but because this can not be done with DOM selector querying, this must be done using the mixitup's `registerFilter()` plugin interface, and requires a bit of custom javascript.

I have a similar example using a range slider here: 

https://demos.kunkalabs.com/mixitup/filtering-by-range/

Note that results are firstly filtered by standard filter controls (using DOM selectors), and then what the additional javascript filter function does is:
- for every matching target:
- tests the value of a `data-size` data attribute on the target against a min and max numeric value provided by the range slider UI

This range could easily be a numeric field instead of a range slider. The key parts of the integration are firstly: a custom `filterTestResult` function, which receives the current test result (`true` to show or `false` to hide), and a reference to the target being tested, and which can then override the test result by returning its own boolean value.

```js
function filterTestResult (testResult, target) {
    // Add your custom range filtering logic here ...
    return testResult;
}
```

And secondly, using MixItup's plugin API to register your custom filter function:

```js
mixitup.Mixer.registerFilter('testResultEvaluateHideShow', 'yourPluginName', filterTestResult)
```

The first argument is the internal "hook" where the filter function should be registered. In this case its 'testResultEvaluateHideShow'.

The second argument is a unique name for your plugin. It can be anything you like.

The third argument is a reference to your function.

I hope that helps.
