### ISSUE TITLE
Speed up animations

### ISSUE THREAD

**Issue by Sebastian-Nielsen** [patrickkunka/mixitup#493]
Your little demo is very fast: https://www.kunkalabs.com/mixitup/

However, after implementing MixItUp on my website, it is quite slow. 

Gif: https://gyazo.com/23fde9ef390be5bde4797b6eb06ad894 (It takes about 1 second for the transition to finish, I would like a shorter transition time)

What might have resulted in this?
How can I speed it up?

Note that I have no other stuff running on the website. I just started from scratch and the first thing I did was to code this little MixItUp thingy.

**Comment by patrickkunka** [comment]
He Sebastian,

I've looked at your video.

Because each mixitup "operation" takes the full amount of time specified in the `animation.duration` configuration option, when you hammer the UI like this, where each click is occurring faster than the time it takes to complete an operation, you end up pushing operations into a queue.

Once one operation ends, the next one from the queue will start and so on until the queue is empty.

If you expect users to interact with your UI like this, there are a few things you could do to prevent long queues building up.

Firstly, and most obviously - reduce the animation duration. It is set to 600ms by default, but you could probably reduce it to around 200 and still provide enough time for nice, smooth UX and transitions. FYI the demo on the website is set at 250ms, which certainly feels snappier.

This can be done via the configuration object when you create your mixitup instance:

```js
var mixer = mixitup(containerEl, {
    animation: {
        duration: 200
    }
});
```

Secondly, you can limit the amount items that can go into the queue. Once the queue is full, subsequent clicks on the UI will be ignored.

The default is 3, but you could reduce it to 1:

```js
var mixer = mixitup(containerEl, {
    animation: {
        queueLimit: 1
    }
});
```

Finally, if animations aren't a requirement for you, you could simply disable them, and have the user interact with your UI synchronously:

```js
var mixer = mixitup(containerEl, {
    animation: {
        enable: false
    }
});
```

Hope that helps!
