### ISSUE TITLE
Multiple Checkbox doesn't give results 

### ISSUE THREAD

**Issue by karthiknmenon** [patrickkunka/mixitup#499]
Whenever I am using multiple checkboxes to filter out results ; the query doesn't work properly. 
In the file attached, I am first categorizing using packages and then using number of days. However If I first choose Package as Mountains and Number of Days as a combination of classes- .2N3 and .3N4, the query displays a combination of packages of class=.Mountains and class=.Beaches 
![1233](https://user-images.githubusercontent.com/41678651/58147057-6db3dd00-7c76-11e9-9a80-1df44e4cfb08.JPG)
![1234](https://user-images.githubusercontent.com/41678651/58147065-74425480-7c76-11e9-9b0d-bae6739a7543.JPG)
![1235](https://user-images.githubusercontent.com/41678651/58147066-74425480-7c76-11e9-857f-6166c1e246e7.JPG)

**Comment by patrickkunka** [comment]
Hello,

Class names cannot start with a number as per the html specification. Querying such classnames will result in a DOM exception.

You should prefix any numeric classnames with one or more letters to avoid this problem.

**Comment by karthiknmenon** [comment]
Hey @patrickkunka , thanks for the quick reply. 
However, even after changing the classnames to alphabetical, the problem still persists.

**Comment by patrickkunka** [comment]
What code are you using to handle your check box selections?

You may want to use the multifilter extension as this will give you handling for inputs like checkboxes out of the box, otherwise you will need to write custom code to handle checkbox selection and selector concatentation.

There is an example here which uses some custom JavaScript:

https://demos.kunkalabs.com/mixitup/checkboxes/

Note that the `value` attribute is used, rather than `data-filter` for a checbox's value.
