### ISSUE TITLE
Multi Filter loading selection and not parse data

### ISSUE THREAD

**Issue by rachelnholtz** [patrickkunka/mixitup#512]
I am creating a filter that rather than it filtering based on the form values for current and desired weight, I need it to run logic first and then filter. I am using parseOn: 'submit' which filters the selected form values, but I need it to run mixer.parseFilterGroups(); first or instead.

I am console logging the output on callback to see the values but I can't seem to get MixItUp to run parseFilterGroups instead. 

Here is the logic I need:
current weight: 50lbs + desired weight: 70lbs = 70lbs
current weight: 50lbs + desired weight: 90lbs = 70lbs & 90lbs
current weight: 70lbs + desired weight: 90lbs = 90lbs

https://codepen.io/rachelholtz/pen/OejOOJ

**Comment by patrickkunka** [comment]
Hi @rachelnholtz 

From what I understand:
- You want to use the multifilter extension to handle the complexities of concatenating selectors between multiple groups.
- However, you don't want to use the multifilter extension's built in UI event handlers, and instead bind your own handlers, run some custom business logic to essentially manipulate the values that the user has selected, and then filter MixItUp via its API.
- You also don't want multifilter to keep the UI in sync with the overridden values created by your custom business logic, as this would create weird UX where form values end up being selected that the user didn't actually select.

To be honest, this is the first time I've come across someone using MultiFilter like this (or only using the concatenation logic part of it), and after thinking about your issue a bit, I think multifilter (wrongly) makes assumptions that a developer wants the extension to handle and control the UI, so there is definitely room for some improvement here.

Nevertheless, in the meantime with a bit of hacking, I think I've got something working which does what you're looking for:

https://codepen.io/anon/pen/dBKegR

- Firstly, I've set `parseOn` to `submit`, as you've already done - which will disable any change event listeners.
- However, we don't actually want it to filter on submit either, so I've changed your `<form>` to a `<div>` to prevent any submit events being fired from a parent of your filter groups.

- Also, as mentioned, we don't want MultiFilter trying to keep your drop downs in sync with your overridden filter values either, so I've removed the `data-filter-group` attributes from your controls so MultiFilter won't be able to see them and manipulate them.
- Instead of listening to a submit event, which will no longer happen, I've bound your custom logic to the `click` event of the submit button.
- Since we still need to use the `setFilterGroupSelectors()` API, MultiFilter does still need to know which groups exist, which is difficult because I had to remove the `data-filter-group` attributes from your UI. To get around this, I've created three empty divs with `data-filter-group` attributes, just to inform MultiFilter about which groups exist.
- I also made a few changes to simplify the passing of arrays to `setFilterGroupSelectors()`, which was broken in your original pen.

It's all a bit hacky, but I hope this is what you're looking for.

**Comment by rachelnholtz** [comment]
Thank you so much for the help this is exactly what I needed. I just removed the parse for the currentMaxWeight because I don't actually need those attributes.

Thanks again for the help!
