### ISSUE TITLE
Save filter states

### ISSUE THREAD

**Issue by ghost** [patrickkunka/mixitup#516]
Is it possible to save the filter states on refresh?

**Comment by patrickkunka** [comment]
Hi there,

Yes, one way of doing this is using a hash segment in your URL that you keep in sync with the current filter selector using MixItUp's callbacks and filter API.

There's a demo here:

https://demos.kunkalabs.com/mixitup/filtering-by-url/#blue

If you're comfortable writing some custom JavaScript, you can adapt this approach to store your values in local storage or save them on the backend via an API instead of using a hash segment.
