### ISSUE TITLE
It just stopped working somehow

### ISSUE THREAD

**Issue by MartinConde** [patrickkunka/mixitup#527]
Hi, I am currently using your library on a wp site I am working on. Everything was working perfectly fine. Today I came back to work on it a bit and it just fails.. I didn't touch the site since the last time it was working (no updates or anything) so I just can't figure out what is wrong.

I tried using the non-minified version instead of the minified one, tried to filter using jQuery instead of html data attributes and re-uploaded the latest version of mixitup.

My filters look like this:

```
<div class="filter" data-filter=".bomber_v_cut">
...
</div>
```
My Grid items:
```
<div class="mix bomber_v_cut" style="visibility: visible;">
...
</div>
```

My initialization:
```
jQuery(document).ready(function(jQuery){

var mixer = mixitup('.pp-custom-grid', {
    selectors: {
        target: '.mix'
    },
    
});
});
```

Any pointers would be much appreciated :)

**Comment by patrickkunka** [comment]
Hi Martin,

Nothing looks wrong with your code, and if you haven't changed anything I suspect your issues are not related to MixItUp.

If this is still an issue, please provide a link to where I can see the issue, or provide any console errors that are related to MixItUp.

FYI - you don't need jQuery to use MixItUp since version 3.
