### ISSUE TITLE
[MixItUp Pagination] Mixing data-attributes causing hidden elements when custom range filtering applied

### ISSUE THREAD

**Issue by msiracusa215** [patrickkunka/mixitup#547]
I've reached out via the contact form about this issue and have not received a response. I am not familiar with GitHub so please let me know if this is the right place for this support request.

I am a marketing manager for a digital marketing agency that is utilizing the paid version of your MixItUp plugin for the website of one of our largest clients.  Our transaction number is 00-5844801-240101. We purchased this only because we thought it would work properly but it is not. The site we are using it on is frannet.com. Specifically, www.frannet.com/franchise-directory which is a directory for a large number of franchise brands.

We are having 2 issues:
1) When we first scroll down, once we are at the 7th block/tile, it hides our initial 6 blocks and doesn't show it no matter what.
2) It is randomly setting display:none to multiple blocks on its own. There is no script set, and you can see I have put numbers in each block/tile, which if you count you will understand that numbers (brands) are missing. It's adding display:none to many blocks on its own. It has nothing to do with cache or js compile or anything, as we  have tested after disabling everything yet are still experiencing the same issue. This issue is coming only after we integrated pagination.

There are over 50 brands which go missing due to this issue so this is a rather serious issue for us and our client. Please advise.

**Comment by patrickkunka** [comment]
Hi @msiracusa215 

Looks like you have some buggy range filter code which is checking if whether the `data-size` attribute of each of your brands (or mixitup "targets") is less than or equal to the current range slider value.

Unfortunately because you have no range filter UI (that I can see), the value that each target is checked against ends up as `0`. It would be better to default this to `Infinity`, if there is no slider.

Because of this, only targets which have an unset `data-size` attribute (`undefined` is effectively equal to `0` in JavaScript) end up being shown.

This is the code:
```js
function filterTestResult(testResult, target) {
    var size = Number(target.dom.el.getAttribute('data-size'));
    var range = Number(document.getElementById("totalinvestment").value); // This `range` var is defaulting to 0
    if (size > range) {
        testResult = !1
    }
    return testResult
}
```

I suspect this is also the cause of your other issues.

Additionally, I noticed you have unnecessary duplication of your `noItemsFoundMessage` element, which appears to be being rendered for every single target item in your mixer. Leading to about 500 unecessary items in your DOM which will negatively affect performance. You only need one of these so I would double check your wordpress templates.

I hope that helps.

**Comment by msiracusa215** [comment]
Thanks for the reply @patrickkunka 

There are 4 filters. Maximum Investment select box filter is used as range slider. 
And that select box's ID is totalinvestment. Script looks fine to me as we have a value of investments in boxes, so this dropdown's value should be higher than box's values.
And this works only when we apply maximum investment filter, and default should be null/ALL, so everything should work fine unless the formula is not correct or I am missing something...

About  noItemsFoundMessage:
I am adding it so when I apply filter and there is no message then it shows up, the structure is such that if I add this div above or anywhere else, it doesn't works, or if you have any better solution please let me know.

Thanks

**Comment by patrickkunka** [comment]
Ah I see - I was looking for a range slider but that makes sense.

The issue is that most of the items in your mixitup container do not have a value set for the `data-size` attribute.

Here's an example:

<img width="545" alt="Screenshot 2020-04-20 at 23 02 23" src="https://user-images.githubusercontent.com/1686556/79804107-3a347380-835b-11ea-8224-48627ef035d0.png">

When the following code is evaluated: 

```js
var size = Number(target.dom.el.getAttribute('data-size'));
```
It returns a `size` of `0`, which is not greater than the default `range` of `0`, so the item is not shown. This is because a data attribute with no value returns an empty string as its value, which is then coerced to `0` by `Number`.

Defaulting `size` to an arbitrarily high number such as `Infinity` (should it evaluate to `0`) should fix it:

```js
var size = Number(target.dom.el.getAttribute('data-size') || Infinity);
```

On the second point, yes you are correct that `noItemsFoundMessage` is probably best placed inside the container, but I am saying that you only need one instance of it (ideally at the start of the container). At the moment you have about 500 instances of it (all with the same ID). This isn't related to the issue you raised, its just an observation and something you may want to fix.

**Comment by msiracusa215** [comment]
Hi @patrickkunka 

We somehow managed to fix the initial issue. Your exact suggestion didn't work for us but it gave us an idea that we used and successfully resolved the issue. Crisis averted!

That being said, regarding the second point and `noItemsFoundMessage` , we're under the impression that MixItUp's structure is such that we have to add this error to every brand, which means that error is added 500+ times.  In order to save us some time, could you explain your solution in more detail? Can you tell us how to show this error just one time when there are no brands available when the filter is applied?

Thanks in advance and thanks for all your help so far!

**Comment by msiracusa215** [comment]
Hi @patrickkunka 

Just following up here. Please let me know how we can implement your solution, thanks!

**Comment by msiracusa215** [comment]
Hi @patrickkunka 

I haven't received a response in about 2 weeks now. Is there another way I should be contacting you regarding this? Please let me know, thanks!

**Comment by patrickkunka** [comment]
Hi @msiracusa215 - I understood that the initial critical issue you were having was resolved, so this issue is closed.

> we're under the impression that MixItUp's structure is such that we have to add this error to every brand, which means that error is added 500+ times

On this point, when mixitup "fails" to find any targets matching the selector, it adds a the classname `mixitup-container-failed`, to the container div.

You can use this classname to conditionally show a hidden error message within the container, but the implementation is entirely up to you. 

A very simple way would be to have a single hidden div containing a fail message (like you have, but just one), and style it to be hidden by default (e.g. `opacity: 0`, `pointer-events: none`, etc), and then use CSS to show it when the aforementioned classname is added. For example:

```css
.fail-message {
    opacity: 0;
    ...
}

.mixitup-container-failed .fail-message {
    opacity: 1;
}
```

You could also show the message with a custom javascript `onMixFail` callback, but css-only is probably the best way.

Either way, there's no need to create a message for every single item in your container. Assuming the content of the message is the same in all circumstances, and you only intend to see one error message at any time, then just hard-code a single fail message in your template at the top of your container, and then loop through "brands" to create your target items only.

I you check out the demo at https://www.kunkalabs.com/mixitup-multifilter/ and select "green", "square" and "small", you will see this technique applied (the classnames have been customised for BEM convention, but its the same approach as described).

<img width="1436" alt="Screenshot 2020-05-04 at 19 56 31" src="https://user-images.githubusercontent.com/1686556/81002577-5ea34c00-8e41-11ea-8d5a-0616a02310cf.png">
