### ISSUE TITLE
Integrate slider UI with mixitup

### ISSUE THREAD

**Issue by povilas123** [patrickkunka/mixitup#6]
Hello,

anyone can help to integrate range Slider UI with Mixitup.
http://jqueryui.com/slider/#range

Template:
http://jsfiddle.net/vSvHM/
Please help to make it work

Or any other range slider to sort price.

Thank you

**Comment by ejlocop** [comment]
Hi, any update on this feature? 

I've managed to filter mixitup items via range slider, but how can i mix it to my current filter strings
if my selector was like ?
```javascript
$('#Container').mixItUp('filter', '.category-1.category2[data-category3=5][data-category4=1]')
```

**Comment by patrickkunka** [comment]
Hi - this has been closed since we launched the v2 filter API which accepts any valid CSS selector.

The idea being that the developer is responsible for building a UI integration that outputs a valid selector string, and MixItUp takes care of the rest.

You'll need to construct some sort of logic that combines the output of your range slider, with your currently applied filters, and outputs a selector string representing your intended output. Unfortunately this very specific functionality is not within the scope of MixItUp, so this is not a feature that would be added to the core.
