### ISSUE TITLE
mixitup related issue

### ISSUE THREAD

**Issue by sancharikasabat** [patrickkunka/mixitup#618]
i can't download it please fix it

**Comment by iecwebmast** [comment]
Dear Sir,

Please provide more information, did you buy a standard and you cannot download it?

Can you please provide the email address that was used to create an account with us?

Best regards,


[Icon  Description automatically generated]<https://www.iec.ch/homepage>
Marcela Gómez
Customer Service Representative

T +41 22 919 0267

IEC - International Electrotechnical Commission
3 rue de Varembé, PO Box 131
CH-1211 Geneva 20, Switzerland

www.iec.ch<https://www.iec.ch/>

***@***.******@***.******@***.***<https://www.linkedin.com/company/international-electrotechnical-commission-iec-> ***@***.*** <https://www.pinterest.com/iecstandards/>  ***@***.*** <https://www.youtube.com/channel/UCxGk_S_rnYyFBcTidgny7EA>  ***@***.*** <https://webstore.iec.ch/>

This message is confidential. It may also be privileged or otherwise protected. If you have received it by mistake, please let us know by e-mail and delete it from your system; you may not copy this message or disclose its contents to anyone. The integrity and security of this message cannot be guaranteed on the Internet.


From: sancharikasabat ***@***.***>
Sent: Thursday, December 14, 2023 4:41 AM
To: patrickkunka/mixitup ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [patrickkunka/mixitup] mixitup related issue (Issue #618)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

i can't download it please fix it

-
